/**
 * GetScorecard DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetQueueScorecardParams } from "@ddd/core/queues";

export function createGetScorecardRequest(overrides: Partial<GetQueueScorecardParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
