/**
 * Roadmap Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RoadmapEntity } from "@ddd/core/portfolio/models/index.js";
import { portfolioSchemas } from "@ddd/core/portfolio";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pfl";

export function createRoadmap(overrides: Partial<RoadmapEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    queueId: overrides.queueId ?? faker.string.uuid(),
    rank: overrides.rank ?? faker.number.int(),
    recommendedAction: overrides.recommendedAction ?? "automate_now",
    ...overrides,
  };

  return portfolioSchemas.RoadmapEntry.parse(raw);
}

export function roadmapBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRoadmap(overrides));
}
