/**
 * GetQueue DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetQueueParams } from "@ddd/core/queues";

export function createGetQueueRequest(overrides: Partial<GetQueueParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
