/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@ddd/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildIdentityDomainModule,
  buildPortfolioDomainModule,
  buildQueuesDomainModule,
  buildRoutingDomainModule,
  buildVendorsDomainModule,
} from "../domains/index.js";
import type {
  IdentityDomainModule,
  PortfolioDomainModule,
  QueuesDomainModule,
  RoutingDomainModule,
  VendorsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private identityModule: IdentityDomainModule | null = null;
  private portfolioModule: PortfolioDomainModule | null = null;
  private queuesModule: QueuesDomainModule | null = null;
  private routingModule: RoutingDomainModule | null = null;
  private vendorsModule: VendorsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get portfolio domain module
   */
  getPortfolioDependencies(): PortfolioDomainModule {
    if (!this.portfolioModule) {
      this.portfolioModule = buildPortfolioDomainModule(this.dynamoClient);
    }
    return this.portfolioModule;
  }

  /**
   * Get queues domain module
   */
  getQueuesDependencies(): QueuesDomainModule {
    if (!this.queuesModule) {
      this.queuesModule = buildQueuesDomainModule(this.dynamoClient);
    }
    return this.queuesModule;
  }

  /**
   * Get routing domain module
   */
  getRoutingDependencies(): RoutingDomainModule {
    if (!this.routingModule) {
      this.routingModule = buildRoutingDomainModule(this.dynamoClient);
    }
    return this.routingModule;
  }

  /**
   * Get vendors domain module
   */
  getVendorsDependencies(): VendorsDomainModule {
    if (!this.vendorsModule) {
      this.vendorsModule = buildVendorsDomainModule(this.dynamoClient);
    }
    return this.vendorsModule;
  }

  clearIdentityDependencies(): void { this.identityModule = null; }
  clearPortfolioDependencies(): void { this.portfolioModule = null; }
  clearQueuesDependencies(): void { this.queuesModule = null; }
  clearRoutingDependencies(): void { this.routingModule = null; }
  clearVendorsDependencies(): void { this.vendorsModule = null; }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getPortfolioDependenciesForRequest(): PortfolioDomainModule {
    return this.getPortfolioDependencies();
  }

  getQueuesDependenciesForRequest(): QueuesDomainModule {
    return this.getQueuesDependencies();
  }

  getRoutingDependenciesForRequest(): RoutingDomainModule {
    return this.getRoutingDependencies();
  }

  getVendorsDependenciesForRequest(): VendorsDomainModule {
    return this.getVendorsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.identityModule = null;
    this.portfolioModule = null;
    this.queuesModule = null;
    this.routingModule = null;
    this.vendorsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
