/**
 * GoldenSet DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GoldenSet DTOs
 *
 * DDD: Application DTOs for GoldenSet use cases.
 */

import type { ListGoldenSetsParams } from "@ddd/core/vendors/types";

export type ListGoldenSetsInput = ListGoldenSetsParams;

export type ListGoldenSetsOutput = {};
