/**
 * VendorCutover DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VendorCutover DTOs
 *
 * DDD: Application DTOs for VendorCutover use cases.
 */

import type { CutoverVendorTrafficParams, CutoverVendorTrafficRequestInput } from "@ddd/core/vendors/types";

export type CutoverVendorTrafficInput = CutoverVendorTrafficParams & CutoverVendorTrafficRequestInput;

export type CutoverVendorTrafficOutput = {};
