/**
 * Vendor DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Vendor DTOs
 *
 * DDD: Application DTOs for Vendor use cases.
 */

import type { ListVendorConnectorsParams, RegisterVendorConnectorRequestInput } from "@ddd/core/vendors/types";

export type ListVendorConnectorsInput = ListVendorConnectorsParams;

export type RegisterVendorConnectorInput = RegisterVendorConnectorRequestInput;

export type ListVendorConnectorsOutput = {};

export type RegisterVendorConnectorOutput = {};
