/**
 * Review Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ReviewEntity } from "@ddd/core/routing/models/index.js";
import { routingSchemas } from "@ddd/core/routing";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rou";

export function createReview(overrides: Partial<ReviewEntity> = {}) {
  const raw = {
    id: overrides.id ?? `hrv_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    decidedAt: overrides.decidedAt ?? new Date().toISOString(),
    decision: overrides.decision ?? "approve",
    reviewerId: overrides.reviewerId ?? faker.string.uuid(),
    workItemId: overrides.workItemId ?? `wit_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return routingSchemas.HumanReview.parse(raw);
}

export function reviewBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createReview(overrides));
}
