/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Queues Domain Use Cases
 * 
 * List of all use case names for the queues domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const QUEUES_USE_CASES = [
  "executeDecideAutomationApproval",
  "executeGetQueue",
  "executeGetQueueScorecard",
  "executeGetThresholdPolicy",
  "executeListQueues",
  "executePinPolicyDefinition",
  "executeRegisterQueue",
  "executeScoreQueue",
  "executeSetThresholdPolicy"
] as const;
