/**
 * GetBenefit DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetBenefitRecordParams } from "@ddd/core/portfolio";

export function createGetBenefitRequest(overrides: Partial<GetBenefitRecordParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
