/**
 * Exposure Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ExposureEntity } from "@ddd/core/portfolio/models/index.js";
import { portfolioSchemas } from "@ddd/core/portfolio";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pfl";

export function createExposure(overrides: Partial<ExposureEntity> = {}) {
  const raw = {
    id: overrides.id ?? `exp_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    agentId: overrides.agentId ?? faker.string.uuid(),
    graphicHandlingMinutes: overrides.graphicHandlingMinutes ?? faker.number.int(),
    period: overrides.period ?? faker.lorem.word(),
    ...overrides,
  };

  return portfolioSchemas.ExposureLedgerEntry.parse(raw);
}

export function exposureBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createExposure(overrides));
}
