/**
 * Handlers for VendorCutover
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { VendorsDomainModule } from "../dependencies/vendors-ddd.dependencies.js";
import type { CutoverVendorTrafficInput } from "@ddd/services/vendors";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/queues/{queueId}/vendor-cutover
 * Operation: cutoverVendorTraffic
 */
export async function cutoverVendorTraffic(
  request: FastifyRequest<{ Params: { queueId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: VendorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CutoverVendorTrafficInput = {
    queueId: request.params.queueId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.vendorCutovers.get.execute(input);
  return reply.code(200).send(result);
}


