/**
 * ExecuteGetQueue - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetQueue Use Case
 *
 * DDD: Application use case for get Queue.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetQueueInput, GetQueueOutput } from "../dto/queue.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { QueueRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetQueue {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly queue: QueueRepository
  ) {}

  async execute(input: GetQueueInput): Promise<GetQueueOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.queId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).queueId) {
      throw new ValidationError("queueId is required");
    }
    const queueId = (input as any).queueId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.queue.getQueue({ queueId: queueId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${queueId}`);
    }

    return entity as GetQueueOutput;
  }
}
