/**
 * ExecuteRegisterQueue - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterQueue Use Case
 *
 * DDD: Application use case for create Queue.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterQueueInput, RegisterQueueOutput } from "../dto/queue.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { QueueRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterQueue {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly queue: QueueRepository
  ) {}

  async execute(input: RegisterQueueInput): Promise<RegisterQueueOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.queId();

    // All field names extracted from OpenAPI spec: averageHandlingTimeSeconds, dailyVolume, impactTier, name, policyDefinitionId, qualityThreshold, taskType, territoryRestrictions
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.taskType) {
      throw new ValidationError("taskType is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.impactTier) {
      throw new ValidationError("impactTier is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (queues domain)
    const entityId = this.idGenerator.queId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.queue.registerQueue({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterQueueOutput;
  }
}
