/**
 * ExecutePinPolicyDefinition - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePinPolicyDefinition Use Case
 *
 * DDD: Application use case for get PolicyDefinition.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PinPolicyDefinitionInput, PinPolicyDefinitionOutput } from "../dto/policy-definition.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { PolicyDefinitionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePinPolicyDefinition {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policyDefinition: PolicyDefinitionRepository
  ) {}

  async execute(input: PinPolicyDefinitionInput): Promise<PinPolicyDefinitionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.queId();

    // All field names extracted from OpenAPI spec: ambiguityNotes, createdAt, id, lastReviewedAt, owner, stability, taxonomyVersion, updatedAt, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).queueId) {
      throw new ValidationError("queueId is required");
    }
    const queueId = (input as any).queueId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.policyDefinition.pinPolicyDefinition({ queueId: queueId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${queueId}`);
    }

    return entity as PinPolicyDefinitionOutput;
  }
}
