/**
 * ExecuteListGoldenSets - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListGoldenSets Use Case
 *
 * DDD: Application use case for list GoldenSet.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListGoldenSetsInput, ListGoldenSetsOutput } from "../dto/golden-set.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { GoldenSetRepository } from "../ports";

export class ExecuteListGoldenSets {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly goldenSet: GoldenSetRepository
  ) {}

  async execute(input: ListGoldenSetsInput): Promise<ListGoldenSetsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vndId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.goldenSet.listGoldenSets({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListGoldenSetsOutput;
  }
}
