/**
 * ExecuteListVendorEvaluations - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListVendorEvaluations Use Case
 *
 * DDD: Application use case for list Evaluation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListVendorEvaluationsInput, ListVendorEvaluationsOutput } from "../dto/evaluation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { EvaluationRepository } from "../ports";

export class ExecuteListVendorEvaluations {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evaluation: EvaluationRepository
  ) {}

  async execute(input: ListVendorEvaluationsInput): Promise<ListVendorEvaluationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vndId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.evaluation.listVendorEvaluations({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListVendorEvaluationsOutput;
  }
}
