/**
 * ExecuteRegisterVendorConnector - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterVendorConnector Use Case
 *
 * DDD: Application use case for create Vendor.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterVendorConnectorInput, RegisterVendorConnectorOutput } from "../dto/vendor.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { VendorClient } from "../ports";
import { ValidationError } from "../errors";

export class ExecuteRegisterVendorConnector {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vendor: VendorClient
  ) {}

  async execute(input: RegisterVendorConnectorInput): Promise<RegisterVendorConnectorOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vndId();

    // All field names extracted from OpenAPI spec: capabilities, contractedAccuracyFloor, name, permittedTerritories, pricePerThousandCalls, processingTermsId, vendorClass
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.capabilities) {
      throw new ValidationError("capabilities is required");
    }

    const result = await this.vendor.registerVendorConnector({
      capabilities: input.capabilities,
      contractedAccuracyFloor: input.contractedAccuracyFloor,
      name: input.name,
      permittedTerritories: input.permittedTerritories,
      pricePerThousandCalls: input.pricePerThousandCalls,
      processingTermsId: input.processingTermsId,
      vendorClass: input.vendorClass,
    });

    return {
      // Response fields
    };
  }
}
