/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { goldenSetRoutes } from "./golden-set.routes.js";
export { vendorRoutes } from "./vendor.routes.js";
export { evaluationRoutes } from "./evaluation.routes.js";
export { vendorCutoverRoutes } from "./vendor-cutover.routes.js";
