/**
 * Routes for VendorCutover
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { cutoverVendorTraffic } from "../handlers/vendor-cutover.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function vendorCutoverRoutes(fastify: FastifyInstance) {
  // POST /v1/queues/{queueId}/vendor-cutover (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/queues/:queueId/vendor-cutover",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { queueId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVendorsDependenciesForRequest();
        await cutoverVendorTraffic(request, reply, deps);
      });
    }
  );


}
