/**
 * Routes for Vendor
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listVendorConnectors, registerVendorConnector } from "../handlers/vendor.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function vendorRoutes(fastify: FastifyInstance) {
  // GET /v1/vendors (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/vendors",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVendorsDependenciesForRequest();
        await listVendorConnectors(request, reply, deps);
      });
    }
  );


  // POST /v1/vendors (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/vendors",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVendorsDependenciesForRequest();
        await registerVendorConnector(request, reply, deps);
      });
    }
  );


}
