/**
 * Handlers for Appeal
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RoutingDomainModule } from "../dependencies/routing-ddd.dependencies.js";
import type { ListAppealsInput, OpenAppealInput } from "@ddd/services/routing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/appeals
 * Operation: listAppeals
 */
export async function listAppeals(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], outcome?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: RoutingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAppealsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.appeals.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/appeals
 * Operation: openAppeal
 */
export async function openAppeal(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: RoutingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenAppealInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.appeals.get.execute(input);
  return reply.code(201).send(result);
}


