/**
 * Handlers for Routing
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RoutingDomainModule } from "../dependencies/routing-ddd.dependencies.js";
import type { GetRoutingDecisionInput } from "@ddd/services/routing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/work-items/{workItemId}/routing
 * Operation: getRoutingDecision
 */
export async function getRoutingDecision(
  request: FastifyRequest<{ Params: { workItemId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RoutingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRoutingDecisionInput = {
    workItemId: request.params.workItemId,
  };
  const result = await deps.useCases.routings.get.execute(input);
  return reply.code(200).send(result);
}


