/**
 * Handlers for WorkItem
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RoutingDomainModule } from "../dependencies/routing-ddd.dependencies.js";
import type { ListWorkItemsInput, SubmitWorkItemInput } from "@ddd/services/routing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/work-items
 * Operation: listWorkItems
 */
export async function listWorkItems(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], queueId?: string | string[], state?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: RoutingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListWorkItemsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.workItems.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/work-items
 * Operation: submitWorkItem
 */
export async function submitWorkItem(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: RoutingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitWorkItemInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.workItems.create.execute(input);
  return reply.code(201).send(result);
}


