/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { appealRoutes } from "./appeal.routes.js";
export { calibrationSampleRoutes } from "./calibration-sample.routes.js";
export { responseClockRoutes } from "./response-clock.routes.js";
export { workItemRoutes } from "./work-item.routes.js";
export { preemptRoutes } from "./preempt.routes.js";
export { resolutionRoutes } from "./resolution.routes.js";
export { reviewRoutes } from "./review.routes.js";
export { rightRoutes } from "./right.routes.js";
export { routingRoutes } from "./routing.routes.js";
