/**
 * Routes for Resolution
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { resolveAppeal } from "../handlers/resolution.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function resolutionRoutes(fastify: FastifyInstance) {
  // POST /v1/appeals/{appealId}/resolution (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/appeals/:appealId/resolution",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { appealId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRoutingDependenciesForRequest();
        await resolveAppeal(request, reply, deps);
      });
    }
  );


}
