/**
 * Routes for Routing
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getRoutingDecision } from "../handlers/routing.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function routingRoutes(fastify: FastifyInstance) {
  // GET /v1/work-items/{workItemId}/routing (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/work-items/:workItemId/routing",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { workItemId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRoutingDependenciesForRequest();
        await getRoutingDecision(request, reply, deps);
      });
    }
  );


}
