/**
 * Queue Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { QueueEntity } from "@ddd/core/queues/models/index.js";
import { queuesSchemas } from "@ddd/core/queues";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "que";

export function createQueue(overrides: Partial<QueueEntity> = {}) {
  const raw = {
    id: overrides.id ?? `que_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    automationStatus: overrides.automationStatus ?? "not_assessed",
    impactTier: overrides.impactTier ?? "critical_illegal",
    name: overrides.name ?? faker.person.fullName(),
    taskType: overrides.taskType ?? "policy_moderation",
    ...overrides,
  };

  return queuesSchemas.Queue.parse(raw);
}

export function queueBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createQueue(overrides));
}
