/**
 * Queues DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Queues Domain Module - Composition root
 *
 * DDD: Composition root for queues domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AutomationApprovalRepositoryAdapter,
  PolicyDefinitionRepositoryAdapter,
  QueueRepositoryAdapter,
  ScorecardRepositoryAdapter,
  ThresholdPolicyRepositoryAdapter,
} from "@ddd/adapters/queues";
import { getIdGeneratorService } from "@ddd/adapters";
import type { AdapterDynamoDBClient } from "@ddd/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDecideAutomationApproval,
  ExecuteGetQueue,
  ExecuteGetQueueScorecard,
  ExecuteGetThresholdPolicy,
  ExecuteListQueues,
  ExecutePinPolicyDefinition,
  ExecuteRegisterQueue,
  ExecuteScoreQueue,
  ExecuteSetThresholdPolicy,
} from "@ddd/services/queues/usecases";
// Ports (interfaces)
import type {
  AutomationApprovalRepository,
  PolicyDefinitionRepository,
  QueueRepository,
  ScorecardRepository,
  ThresholdPolicyRepository,
} from "@ddd/services/queues/ports";

export interface QueuesDomainModule {
  repos: {
    automationApprovals: AutomationApprovalRepository;
    policyDefinitions: PolicyDefinitionRepository;
    queues: QueueRepository;
    scorecards: ScorecardRepository;
    thresholdPolicies: ThresholdPolicyRepository;
  };
  useCases: {
    automationApprovals: {
      get: ExecuteDecideAutomationApproval;
    };
    policyDefinitions: {
      get: ExecutePinPolicyDefinition;
    };
    queues: {
      create: ExecuteRegisterQueue;
      get: ExecuteGetQueue;
      list: ExecuteListQueues;
    };
    scorecards: {
      get: ExecuteScoreQueue;
    };
    thresholdPolicies: {
      get: ExecuteGetThresholdPolicy;
      update: ExecuteSetThresholdPolicy;
    };
  };
}

export function buildQueuesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): QueuesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      automationApprovals?: AutomationApprovalRepository;
      policyDefinitions?: PolicyDefinitionRepository;
      queues?: QueueRepository;
      scorecards?: ScorecardRepository;
      thresholdPolicies?: ThresholdPolicyRepository;
    } = {};

    obj.automationApprovals = new AutomationApprovalRepositoryAdapter(dynamoClient);
    obj.policyDefinitions = new PolicyDefinitionRepositoryAdapter(dynamoClient);
    obj.queues = new QueueRepositoryAdapter(dynamoClient);
    obj.scorecards = new ScorecardRepositoryAdapter(dynamoClient);
    obj.thresholdPolicies = new ThresholdPolicyRepositoryAdapter(dynamoClient);
    return {
      automationApprovals: obj.automationApprovals!,
      policyDefinitions: obj.policyDefinitions!,
      queues: obj.queues!,
      scorecards: obj.scorecards!,
      thresholdPolicies: obj.thresholdPolicies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    automationApprovals: {
      get: new ExecuteDecideAutomationApproval(executionContext, idGenerator, repos.automationApprovals),
    },
    policyDefinitions: {
      get: new ExecutePinPolicyDefinition(executionContext, idGenerator, repos.policyDefinitions),
    },
    queues: {
      create: new ExecuteRegisterQueue(executionContext, idGenerator, repos.queues),
      get: new ExecuteGetQueue(executionContext, idGenerator, repos.queues),
      list: new ExecuteListQueues(executionContext, idGenerator, repos.queues),
    },
    scorecards: {
      get: new ExecuteScoreQueue(executionContext, idGenerator, repos.scorecards),
    },
    thresholdPolicies: {
      get: new ExecuteGetThresholdPolicy(executionContext, idGenerator, repos.thresholdPolicies),
      update: new ExecuteSetThresholdPolicy(executionContext, idGenerator, repos.thresholdPolicies),
    },
  };
  return { repos, useCases: useCases as QueuesDomainModule["useCases"] };
}
