/**
 * Scorecard Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ScorecardEntity } from "@ddd/core/queues/models/index.js";
import { queuesSchemas } from "@ddd/core/queues";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "que";

export function createScorecard(overrides: Partial<ScorecardEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    queueId: overrides.queueId ?? `que_${ulid().toLowerCase()}`,
    scoredAt: overrides.scoredAt ?? new Date().toISOString(),
    weightedScore: overrides.weightedScore ?? faker.number.int(),
    ...overrides,
  };

  return queuesSchemas.QueueScorecard.parse(raw);
}

export function scorecardBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createScorecard(overrides));
}
