/**
 * EgressRecordRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EgressRecordRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EgressRecordRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EgressRecordRepository,
} from "@ddd/services/portfolio";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EgressRecordRepositoryDdb } from "./egress-record-repository.ddb.js";

/**
 * EgressRecordRepositoryAdapter
 *
 * Implements EgressRecordRepository port for infrastructure layer.
 */
export class EgressRecordRepositoryAdapter implements EgressRecordRepository {
  private readonly ddb: EgressRecordRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EgressRecordRepositoryDdb(this.dynamoClient);
  }

  async listEgressRecords(input: Parameters<EgressRecordRepository['listEgressRecords']>[0]): Promise<Awaited<ReturnType<EgressRecordRepository['listEgressRecords']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEgressRecords(input);
  }
}
