/**
 * ExposureRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExposureRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExposureRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExposureRepository,
} from "@ddd/services/portfolio";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExposureRepositoryDdb } from "./exposure-repository.ddb.js";

/**
 * ExposureRepositoryAdapter
 *
 * Implements ExposureRepository port for infrastructure layer.
 */
export class ExposureRepositoryAdapter implements ExposureRepository {
  private readonly ddb: ExposureRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExposureRepositoryDdb(this.dynamoClient);
  }

  async getExposureLedger(input: Parameters<ExposureRepository['getExposureLedger']>[0]): Promise<Awaited<ReturnType<ExposureRepository['getExposureLedger']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getExposureLedger(input);
  }
}
