/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./benefit-repository.ddb.js";
export * from "./egress-record-repository.ddb.js";
export * from "./exposure-repository.ddb.js";
export * from "./rescore-repository.ddb.js";
export * from "./roadmap-repository.ddb.js";
export * from "./benefit-repository.adapter.js";
export * from "./egress-record-repository.adapter.js";
export * from "./exposure-repository.adapter.js";
export * from "./rescore-repository.adapter.js";
export * from "./roadmap-repository.adapter.js";
