/**
 * RoadmapRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RoadmapRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RoadmapRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RoadmapRepository,
} from "@ddd/services/portfolio";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RoadmapRepositoryDdb } from "./roadmap-repository.ddb.js";

/**
 * RoadmapRepositoryAdapter
 *
 * Implements RoadmapRepository port for infrastructure layer.
 */
export class RoadmapRepositoryAdapter implements RoadmapRepository {
  private readonly ddb: RoadmapRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RoadmapRepositoryDdb(this.dynamoClient);
  }

  async listRoadmapEntries(input: Parameters<RoadmapRepository['listRoadmapEntries']>[0]): Promise<Awaited<ReturnType<RoadmapRepository['listRoadmapEntries']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRoadmapEntries(input);
  }
}
