/**
 * AutomationApprovalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AutomationApprovalRepository Port
 *
 * DDD: Application port for automationapprovalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DecideAutomationApprovalInput, DecideAutomationApprovalOutput } from "../dto/automation-approval.dto";
export interface AutomationApprovalRepository {
  decideAutomationApproval(input: DecideAutomationApprovalInput): Promise<DecideAutomationApprovalOutput>;
}

export type { DecideAutomationApprovalInput, DecideAutomationApprovalOutput } from "../dto/automation-approval.dto";
