/**
 * PolicyDefinitionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyDefinitionRepository Port
 *
 * DDD: Application port for policydefinitionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PinPolicyDefinitionInput, PinPolicyDefinitionOutput } from "../dto/policy-definition.dto";
export interface PolicyDefinitionRepository {
  pinPolicyDefinition(input: PinPolicyDefinitionInput): Promise<PinPolicyDefinitionOutput>;
}

export type { PinPolicyDefinitionInput, PinPolicyDefinitionOutput } from "../dto/policy-definition.dto";
