/**
 * QueueRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QueueRepository Port
 *
 * DDD: Application port for queuerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetQueueInput, GetQueueOutput, ListQueuesInput, ListQueuesOutput, RegisterQueueInput, RegisterQueueOutput } from "../dto/queue.dto";
export interface QueueRepository {
  listQueues(input: ListQueuesInput): Promise<ListQueuesOutput>;
  registerQueue(input: RegisterQueueInput): Promise<RegisterQueueOutput>;
  getQueue(input: GetQueueInput): Promise<GetQueueOutput>;
}

export type { GetQueueInput, GetQueueOutput, ListQueuesInput, ListQueuesOutput, RegisterQueueInput, RegisterQueueOutput } from "../dto/queue.dto";
