/**
 * ScorecardRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScorecardRepository Port
 *
 * DDD: Application port for scorecardrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetQueueScorecardInput, GetQueueScorecardOutput, ScoreQueueInput, ScoreQueueOutput } from "../dto/scorecard.dto";
export interface ScorecardRepository {
  getQueueScorecard(input: GetQueueScorecardInput): Promise<GetQueueScorecardOutput>;
  scoreQueue(input: ScoreQueueInput): Promise<ScoreQueueOutput>;
}

export type { GetQueueScorecardInput, GetQueueScorecardOutput, ScoreQueueInput, ScoreQueueOutput } from "../dto/scorecard.dto";
