/**
 * ThresholdPolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ThresholdPolicyRepository Port
 *
 * DDD: Application port for thresholdpolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetThresholdPolicyInput, GetThresholdPolicyOutput, SetThresholdPolicyInput, SetThresholdPolicyOutput } from "../dto/threshold-policy.dto";
export interface ThresholdPolicyRepository {
  getThresholdPolicy(input: GetThresholdPolicyInput): Promise<GetThresholdPolicyOutput>;
  setThresholdPolicy(input: SetThresholdPolicyInput): Promise<SetThresholdPolicyOutput>;
}

export type { GetThresholdPolicyInput, GetThresholdPolicyOutput, SetThresholdPolicyInput, SetThresholdPolicyOutput } from "../dto/threshold-policy.dto";
