/**
 * ListGoldenSet DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListGoldenSetsParams } from "@ddd/core/vendors";

export function createListGoldenSetRequest(overrides: Partial<ListGoldenSetsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
