/**
 * ResponseClock Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ResponseClockEntity } from "@ddd/core/routing/models/index.js";
import { routingSchemas } from "@ddd/core/routing";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rou";

export function createResponseClock(overrides: Partial<ResponseClockEntity> = {}) {
  const raw = {
    id: overrides.id ?? `clk_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    clockType: overrides.clockType ?? "statutory_removal",
    dueAt: overrides.dueAt ?? new Date().toISOString(),
    status: overrides.status ?? "running",
    workItemId: overrides.workItemId ?? `wit_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return routingSchemas.ResponseClock.parse(raw);
}

export function responseClockBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createResponseClock(overrides));
}
