/**
 * Benefit Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { BenefitEntity } from "@ddd/core/portfolio/models/index.js";
import { portfolioSchemas } from "@ddd/core/portfolio";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pfl";

export function createBenefit(overrides: Partial<BenefitEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    period: overrides.period ?? faker.lorem.word(),
    queueId: overrides.queueId ?? faker.string.uuid(),
    ...overrides,
  };

  return portfolioSchemas.BenefitRecord.parse(raw);
}

export function benefitBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createBenefit(overrides));
}
