/**
 * GetRouting DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetRoutingDecisionParams } from "@ddd/core/routing";

export function createGetRoutingRequest(overrides: Partial<GetRoutingDecisionParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
