/**
 * GoldenSet Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { GoldenSetEntity } from "@ddd/core/vendors/models/index.js";
import { vendorsSchemas } from "@ddd/core/vendors";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "vnd";

export function createGoldenSet(overrides: Partial<GoldenSetEntity> = {}) {
  const raw = {
    id: overrides.id ?? `gld_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    itemCount: overrides.itemCount ?? faker.number.int({ min: 1, max: 100 }),
    queueId: overrides.queueId ?? faker.string.uuid(),
    ...overrides,
  };

  return vendorsSchemas.GoldenSet.parse(raw);
}

export function goldenSetBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createGoldenSet(overrides));
}
