/**
 * Resolution Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/routing.openapi.types.js";
import { schemas } from "../schemas/routing.schemas.js";

/**
 * Entity: ResolutionEntity
 * Description: Represents the Resolution domain model.
 * Source: schemas.Appeal
 * Type: Persisted Entity (x-dynamodb)
 */
export const ResolutionEntitySchema = schemas.Appeal;
export type ResolutionEntity = components["schemas"]["Appeal"];
