/**
 * ResponseClock Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/routing.openapi.types.js";
import { schemas } from "../schemas/routing.schemas.js";

/**
 * Entity: ResponseClockEntity
 * Description: Represents the ResponseClock domain model.
 * Source: schemas.ResponseClock
 * Type: Persisted Entity (x-dynamodb)
 */
export const ResponseClockEntitySchema = schemas.ResponseClock;
export type ResponseClockEntity = components["schemas"]["ResponseClock"];
