/**
 * Right Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/routing.openapi.types.js";
import { schemas } from "../schemas/routing.schemas.js";

/**
 * Entity: RightEntity
 * Description: Represents the Right domain model.
 * Source: schemas.RightsRecord
 * Type: Persisted Entity (x-dynamodb)
 */
export const RightEntitySchema = schemas.RightsRecord;
export type RightEntity = components["schemas"]["RightsRecord"];
