/**
 * Routing Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/routing.openapi.types.js";
import { schemas } from "../schemas/routing.schemas.js";

/**
 * Entity: RoutingEntity
 * Description: Represents the Routing domain model.
 * Source: schemas.RoutingDecision
 * Type: Persisted Entity (x-dynamodb)
 */
export const RoutingEntitySchema = schemas.RoutingDecision;
export type RoutingEntity = components["schemas"]["RoutingDecision"];
