/**
 * GetRightsRecord handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRightsRecord } from "@ddd/api-server/domains/routing/handlers";
import type { RoutingDDDDependencies } from "@ddd/api-server/domains/routing";
import { createRight as createRightEntity } from "@ddd/factories/routing";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ddd/tests/shared";
import { ROUTING_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRightsRecord", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RoutingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RoutingDDDDependencies>(
      ROUTING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createRightEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRightsRecord, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { workItemId: entity.id };

    await getRightsRecord(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRightsRecord.execute).toHaveBeenCalledWith(expect.objectContaining({ workItemId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { workItemId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRightsRecord, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRightsRecord(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
