/**
 * Repository interface for GoldenSet
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  GoldenSetEntity
} from "../models/golden-set.entity.js";
import type {
  ListGoldenSetsParams
} from "../types/index.js";
/**
 * GoldenSetRepository Interface
 */
export interface GoldenSetRepository extends ReadRepository<GoldenSetEntity, string, ListGoldenSetsParams> {

}
