/**
 * Repository interface for AutomationApproval
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AutomationApprovalEntity
} from "../models/automation-approval.entity.js";
import type {
  Queue
} from "../types/index.js";
/**
 * AutomationApprovalRepository Interface
 */
export interface AutomationApprovalRepository extends CreateReadRepository<AutomationApprovalEntity, Queue, string, Record<string, never>> {

}
