/**
 * Repository interface for PolicyDefinition
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PolicyDefinitionEntity
} from "../models/policy-definition.entity.js";
import type {
  PinPolicyDefinitionRequestInput
} from "../types/index.js";
/**
 * PolicyDefinitionRepository Interface
 */
export interface PolicyDefinitionRepository extends UpdateReadRepository<PolicyDefinitionEntity, PinPolicyDefinitionRequestInput, string, Record<string, never>> {

}
