/**
 * Repository interface for Queue
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  QueueEntity
} from "../models/queue.entity.js";
import type {
  ListQueuesParams,
  Queue
} from "../types/index.js";
/**
 * QueueRepository Interface
 */
export interface QueueRepository extends CreateReadRepository<QueueEntity, Queue, string, ListQueuesParams> {

}
