/**
 * Repository interface for ThresholdPolicy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ThresholdPolicyEntity
} from "../models/threshold-policy.entity.js";
import type {
  SetThresholdPolicyRequestInput
} from "../types/index.js";
/**
 * ThresholdPolicyRepository Interface
 */
export interface ThresholdPolicyRepository extends UpdateReadRepository<ThresholdPolicyEntity, SetThresholdPolicyRequestInput, string, Record<string, never>> {

}
