/**
 * GoldenSet Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/vendors.openapi.types.js";
import { schemas } from "../schemas/vendors.schemas.js";

/**
 * Entity: GoldenSetEntity
 * Description: Represents the GoldenSet domain model.
 * Source: schemas.GoldenSet
 * Type: Persisted Entity (x-dynamodb)
 */
export const GoldenSetEntitySchema = schemas.GoldenSet;
export type GoldenSetEntity = components["schemas"]["GoldenSet"];
