/**
 * Vendor Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/vendors.openapi.types.js";
import { schemas } from "../schemas/vendors.schemas.js";

/**
 * Entity: VendorEntity
 * Description: Represents the Vendor domain model.
 * Source: schemas.VendorConnector
 * Type: Persisted Entity (x-dynamodb)
 */
export const VendorEntitySchema = schemas.VendorConnector;
export type VendorEntity = components["schemas"]["VendorConnector"];
