/**
 * ExecuteListAppeals - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAppeals Use Case
 *
 * DDD: Application use case for list Appeal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAppealsInput, ListAppealsOutput } from "../dto/appeal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { AppealRepository } from "../ports";

export class ExecuteListAppeals {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly appeal: AppealRepository
  ) {}

  async execute(input: ListAppealsInput): Promise<ListAppealsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rouId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.appeal.listAppeals({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAppealsOutput;
  }
}
