/**
 * ExecuteResolveAppeal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteResolveAppeal Use Case
 *
 * DDD: Application use case for get Resolution.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ResolveAppealInput, ResolveAppealOutput } from "../dto/resolution.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { ResolutionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteResolveAppeal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly resolution: ResolutionRepository
  ) {}

  async execute(input: ResolveAppealInput): Promise<ResolveAppealOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rouId();

    // All field names extracted from OpenAPI spec: feedsCalibrationSet, outcome, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).appealId) {
      throw new ValidationError("appealId is required");
    }
    const appealId = (input as any).appealId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.resolution.resolveAppeal({ appealId: appealId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${appealId}`);
    }

    return entity as ResolveAppealOutput;
  }
}
