/**
 * ExecuteOpenAppeal - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenAppeal Use Case
 *
 * DDD: Application use case for get Appeal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenAppealInput, OpenAppealOutput } from "../dto/appeal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { AppealRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenAppeal {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly appeal: AppealRepository
  ) {}

  async execute(input: OpenAppealInput): Promise<OpenAppealOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rouId();

    // All field names extracted from OpenAPI spec: evidence, grounds, raisedBy, workItemId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).workItemId) {
      throw new ValidationError("workItemId is required");
    }
    const workitemId = (input as any).workItemId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.appeal.openAppeal({ workItemId: workitemId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${workitemId}`);
    }

    return entity as OpenAppealOutput;
  }
}
