/**
 * ExecuteListWorkItems - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListWorkItems Use Case
 *
 * DDD: Application use case for list WorkItem.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListWorkItemsInput, ListWorkItemsOutput } from "../dto/work-item.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { WorkItemRepository } from "../ports";

export class ExecuteListWorkItems {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly workItem: WorkItemRepository
  ) {}

  async execute(input: ListWorkItemsInput): Promise<ListWorkItemsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rouId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.workItem.listWorkItems({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListWorkItemsOutput;
  }
}
