/**
 * ExecuteListResponseClocks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListResponseClocks Use Case
 *
 * DDD: Application use case for list ResponseClock.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListResponseClocksInput, ListResponseClocksOutput } from "../dto/response-clock.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { ResponseClockRepository } from "../ports";

export class ExecuteListResponseClocks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly responseClock: ResponseClockRepository
  ) {}

  async execute(input: ListResponseClocksInput): Promise<ListResponseClocksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rouId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.responseClock.listResponseClocks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListResponseClocksOutput;
  }
}
