/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @ddd/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@ddd/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@ddd/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@ddd/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@ddd/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@ddd/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _identity from "./identity/index.js";
import * as _portfolio from "./portfolio/index.js";
import * as _queues from "./queues/index.js";
import * as _routing from "./routing/index.js";
import * as _vendors from "./vendors/index.js";

// Export as namespaces
export const _shared = __shared;
export const identity = _identity;
export const portfolio = _portfolio;
export const queues = _queues;
export const routing = _routing;
export const vendors = _vendors;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@ddd/core"; activity.types.*
//   - Direct exports: import * from "@ddd/core/activity/types/index.js"
//   - Direct exports: import * from "@ddd/core/activity/repositories/index.js"
//   - Direct exports: import * from "@ddd/core/activity/models/index.js"
//   - Direct exports: import * from "@ddd/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Portfolio Service
export { schemas as PortfolioSchemas } from "./portfolio/schemas/portfolio.schemas.js";

// Queues Service
export { schemas as QueuesSchemas } from "./queues/schemas/queues.schemas.js";

// Routing Service
export { schemas as RoutingSchemas } from "./routing/schemas/routing.schemas.js";

// Vendors Service
export { schemas as VendorsSchemas } from "./vendors/schemas/vendors.schemas.js";

