/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Routing Domain Use Cases
 * 
 * List of all use case names for the routing domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ROUTING_USE_CASES = [
  "executeGetRightsRecord",
  "executeGetRoutingDecision",
  "executeListAppeals",
  "executeListCalibrationSamples",
  "executeListResponseClocks",
  "executeListWorkItems",
  "executeOpenAppeal",
  "executePreemptResponseClock",
  "executeRecordHumanReview",
  "executeResolveAppeal",
  "executeSubmitWorkItem"
] as const;
