/**
 * PolicyDefinition Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PolicyDefinitionEntity } from "@ddd/core/queues/models/index.js";
import { queuesSchemas } from "@ddd/core/queues";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "que";

export function createPolicyDefinition(overrides: Partial<PolicyDefinitionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    stability: overrides.stability ?? "stable",
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return queuesSchemas.PolicyDefinition.parse(raw);
}

export function policyDefinitionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPolicyDefinition(overrides));
}
