/**
 * Handlers for PolicyDefinition
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { QueuesDomainModule } from "../dependencies/queues-ddd.dependencies.js";
import type { PinPolicyDefinitionInput } from "@ddd/services/queues";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v1/queues/{queueId}/policy-definition
 * Operation: pinPolicyDefinition
 */
export async function pinPolicyDefinition(
  request: FastifyRequest<{ Params: { queueId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: QueuesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: PinPolicyDefinitionInput = {
    queueId: request.params.queueId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.policyDefinitions.get.execute(input);
  return reply.code(200).send(result);
}


