/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Vendors Domain Use Cases
 * 
 * List of all use case names for the vendors domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const VENDORS_USE_CASES = [
  "executeCutoverVendorTraffic",
  "executeListGoldenSets",
  "executeListVendorConnectors",
  "executeListVendorEvaluations",
  "executeRegisterVendorConnector",
  "executeStartVendorEvaluation"
] as const;
