/**
 * Repository interface for Appeal
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AppealEntity
} from "../models/appeal.entity.js";
import type {
  ListAppealsParams,
  Appeal
} from "../types/index.js";
/**
 * AppealRepository Interface
 */
export interface AppealRepository extends CreateReadRepository<AppealEntity, Appeal, string, ListAppealsParams> {

}
