/**
 * Repository interface for Preempt
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PreemptEntity
} from "../models/preempt.entity.js";
import type {
  ResponseClock
} from "../types/index.js";
/**
 * PreemptRepository Interface
 */
export interface PreemptRepository extends CreateReadRepository<PreemptEntity, ResponseClock, string, Record<string, never>> {

}
