/**
 * Repository interface for Resolution
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ResolutionEntity
} from "../models/resolution.entity.js";
import type {
  Appeal
} from "../types/index.js";
/**
 * ResolutionRepository Interface
 */
export interface ResolutionRepository extends CreateReadRepository<ResolutionEntity, Appeal, string, Record<string, never>> {

}
