/**
 * Repository interface for ResponseClock
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ResponseClockEntity
} from "../models/response-clock.entity.js";
import type {
  ListResponseClocksParams
} from "../types/index.js";
/**
 * ResponseClockRepository Interface
 */
export interface ResponseClockRepository extends ReadRepository<ResponseClockEntity, string, ListResponseClocksParams> {

}
