/**
 * Repository interface for Routing
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RoutingEntity
} from "../models/routing.entity.js";
/**
 * RoutingRepository Interface
 */
export interface RoutingRepository extends ReadRepository<RoutingEntity, string, Record<string, never>> {

}
