/**
 * Repository interface for WorkItem
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  WorkItemEntity
} from "../models/work-item.entity.js";
import type {
  ListWorkItemsParams,
  WorkItem
} from "../types/index.js";
/**
 * WorkItemRepository Interface
 */
export interface WorkItemRepository extends CreateReadRepository<WorkItemEntity, WorkItem, string, ListWorkItemsParams> {

}
