/**
 * Benefit Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/portfolio.openapi.types.js";
import { schemas } from "../schemas/portfolio.schemas.js";

/**
 * Entity: BenefitEntity
 * Description: Represents the Benefit domain model.
 * Source: schemas.BenefitRecord
 * Type: Persisted Entity (x-dynamodb)
 */
export const BenefitEntitySchema = schemas.BenefitRecord;
export type BenefitEntity = components["schemas"]["BenefitRecord"];
