/**
 * Roadmap Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/portfolio.openapi.types.js";
import { schemas } from "../schemas/portfolio.schemas.js";

/**
 * Entity: RoadmapEntity
 * Description: Represents the Roadmap domain model.
 * Source: schemas.RoadmapEntry
 * Type: Persisted Entity (x-dynamodb)
 */
export const RoadmapEntitySchema = schemas.RoadmapEntry;
export type RoadmapEntity = components["schemas"]["RoadmapEntry"];
