/**
 * AutomationApprovalRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AutomationApprovalRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AutomationApprovalRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AutomationApprovalRepository,
} from "@ddd/services/queues";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AutomationApprovalRepositoryDdb } from "./automation-approval-repository.ddb.js";

/**
 * AutomationApprovalRepositoryAdapter
 *
 * Implements AutomationApprovalRepository port for infrastructure layer.
 */
export class AutomationApprovalRepositoryAdapter implements AutomationApprovalRepository {
  private readonly ddb: AutomationApprovalRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AutomationApprovalRepositoryDdb(this.dynamoClient);
  }

  async decideAutomationApproval(input: Parameters<AutomationApprovalRepository['decideAutomationApproval']>[0]): Promise<Awaited<ReturnType<AutomationApprovalRepository['decideAutomationApproval']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.decideAutomationApproval(input);
  }
}
