/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./automation-approval-repository.ddb.js";
export * from "./policy-definition-repository.ddb.js";
export * from "./queue-repository.ddb.js";
export * from "./scorecard-repository.ddb.js";
export * from "./threshold-policy-repository.ddb.js";
export * from "./automation-approval-repository.adapter.js";
export * from "./policy-definition-repository.adapter.js";
export * from "./queue-repository.adapter.js";
export * from "./scorecard-repository.adapter.js";
export * from "./threshold-policy-repository.adapter.js";
