/**
 * PolicyDefinitionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyDefinitionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PolicyDefinitionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PolicyDefinitionRepository,
} from "@ddd/services/queues";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PolicyDefinitionRepositoryDdb } from "./policy-definition-repository.ddb.js";

/**
 * PolicyDefinitionRepositoryAdapter
 *
 * Implements PolicyDefinitionRepository port for infrastructure layer.
 */
export class PolicyDefinitionRepositoryAdapter implements PolicyDefinitionRepository {
  private readonly ddb: PolicyDefinitionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PolicyDefinitionRepositoryDdb(this.dynamoClient);
  }

  async pinPolicyDefinition(input: Parameters<PolicyDefinitionRepository['pinPolicyDefinition']>[0]): Promise<Awaited<ReturnType<PolicyDefinitionRepository['pinPolicyDefinition']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.pinPolicyDefinition(input);
  }
}
