/**
 * QueueRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QueueRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements QueueRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  QueueRepository,
} from "@ddd/services/queues";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { QueueRepositoryDdb } from "./queue-repository.ddb.js";

/**
 * QueueRepositoryAdapter
 *
 * Implements QueueRepository port for infrastructure layer.
 */
export class QueueRepositoryAdapter implements QueueRepository {
  private readonly ddb: QueueRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new QueueRepositoryDdb(this.dynamoClient);
  }

  async listQueues(input: Parameters<QueueRepository['listQueues']>[0]): Promise<Awaited<ReturnType<QueueRepository['listQueues']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listQueues(input);
  }

  async registerQueue(input: Parameters<QueueRepository['registerQueue']>[0]): Promise<Awaited<ReturnType<QueueRepository['registerQueue']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerQueue(input);
  }

  async getQueue(input: Parameters<QueueRepository['getQueue']>[0]): Promise<Awaited<ReturnType<QueueRepository['getQueue']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getQueue(input);
  }
}
