/**
 * ScorecardRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScorecardRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ScorecardRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ScorecardRepository,
} from "@ddd/services/queues";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ScorecardRepositoryDdb } from "./scorecard-repository.ddb.js";

/**
 * ScorecardRepositoryAdapter
 *
 * Implements ScorecardRepository port for infrastructure layer.
 */
export class ScorecardRepositoryAdapter implements ScorecardRepository {
  private readonly ddb: ScorecardRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ScorecardRepositoryDdb(this.dynamoClient);
  }

  async getQueueScorecard(input: Parameters<ScorecardRepository['getQueueScorecard']>[0]): Promise<Awaited<ReturnType<ScorecardRepository['getQueueScorecard']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getQueueScorecard(input);
  }

  async scoreQueue(input: Parameters<ScorecardRepository['scoreQueue']>[0]): Promise<Awaited<ReturnType<ScorecardRepository['scoreQueue']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.scoreQueue(input);
  }
}
