/**
 * ThresholdPolicyRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ThresholdPolicyRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing ThresholdPolicy repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { ThresholdPolicyRepository } from "@ddd/services/queues";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * ThresholdPolicyRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: THRESHOLD_POLICY
 * Entity Token: THRESHOLD_POLICY
 * SK Prefix: THRESHOLD_POLICY
 */
export class ThresholdPolicyRepositoryDdb implements ThresholdPolicyRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "THRESHOLD_POLICY";
  private readonly ENTITY_TOKEN = "THRESHOLD_POLICY";
  private readonly SK_PREFIX = "THRESHOLD_POLICY";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "createdAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "QUEUES";
  private readonly ENTITY_TYPE_PK = "THRESHOLD_POLICYS";
  private generateCorrelationId(): string {
    const domainPrefix = "que";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async getThresholdPolicy(input: Parameters<ThresholdPolicyRepository['getThresholdPolicy']>[0]): Promise<Awaited<ReturnType<ThresholdPolicyRepository['getThresholdPolicy']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input) {
      throw new Error("Missing required parameter: input");
    }
    if (!(inputExt.queueId ?? inputExt.id ?? inputExt.queueId)) {
      throw new Error("Missing required parameter: queueId");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const pk = this.buildPK(inputExt.orgId as string, (inputExt.queueId ?? inputExt.id ?? inputExt.queueId) as string);
    // Soft-delete layout prefixes SK with ACTIVE# when statusPrefix is enabled.
    const skPrefix = `${this.ENTITY_TOKEN}#${(inputExt.queueId ?? inputExt.id ?? inputExt.queueId)}#`;
    const result = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      KeyConditionExpression: "PK = :pk AND begins_with(SK, :skPrefix)",
      ExpressionAttributeValues: { ":pk": pk, ":skPrefix": skPrefix },
      Limit: 1,
    });
    const item = result.Items?.[0];
    if (!item) {
      throw new Error(`${this.ENTITY_TYPE} with id ${(inputExt.queueId ?? inputExt.id ?? inputExt.queueId)} not found`);
    }
    return {
      data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }

  async setThresholdPolicy(input: Parameters<ThresholdPolicyRepository['setThresholdPolicy']>[0]): Promise<Awaited<ReturnType<ThresholdPolicyRepository['setThresholdPolicy']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!inputExt.queueId) {
      throw new Error("Missing required parameter: queueId");
    }
    if (!inputExt.orgId) {
      throw new Error("Missing required parameter: orgId");
    }
    const pk = this.buildPK(inputExt.orgId as string, inputExt.queueId as string);
    const getResult = await this.dynamoClient.query({
      TableName: this.TABLE_NAME,
      KeyConditionExpression: "PK = :pk AND begins_with(SK, :skPrefix)",
      ExpressionAttributeValues: { ":pk": pk, ":skPrefix": `${this.ENTITY_TOKEN}#${inputExt.queueId}#` },
      ScanIndexForward: false,
      Limit: 1,
    });
    const existing = getResult.Items?.[0] as Record<string, unknown> | undefined;
    const now = new Date().toISOString();
    if (!existing?.PK || !existing?.SK) {
      // Upsert: create when missing (PUT semantics)
      const pkNew = this.buildPK(inputExt.orgId as string, inputExt.queueId as string);
      const skNew = this.buildSK(inputExt.queueId as string);
      const item = {
        ...(input as Record<string, unknown>),
        queueId: inputExt.queueId,
        PK: pkNew,
        SK: skNew,
        entityType: this.ENTITY_TYPE,
        [this.CREATED_AT_FIELD]: now,
        [this.UPDATED_AT_FIELD]: now,
        "GSI2-PK": this.buildGSI2PK(inputExt.orgId as string),
        "GSI2-SK": this.buildGsiSK(now, inputExt.queueId as string),
      };
      await this.dynamoClient.put({
        TableName: this.TABLE_NAME,
        Item: item,
      });
      return {
        data: sanitizeItem(item as Record<string, unknown>) as unknown as any,
        meta: {
          correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
          timestamp: new Date().toISOString(),
        } as unknown as any,
      };
    }
    const updateExpressions: string[] = [`#${this.UPDATED_AT_FIELD} = :updatedAt`];
    const expressionAttributeNames: Record<string, string> = { [`#${this.UPDATED_AT_FIELD}`]: this.UPDATED_AT_FIELD };
    const expressionAttributeValues: Record<string, unknown> = { ":updatedAt": now };
    Object.keys(input || {}).forEach((key, index) => {
      if (key !== "queueId" && key !== "orgId" && key !== "correlationId") {
        const nameKey = `#field${index}`;
        const valueKey = `:value${index}`;
        updateExpressions.push(`${nameKey} = ${valueKey}`);
        expressionAttributeNames[nameKey] = key;
        expressionAttributeValues[valueKey] = inputExt[key];
      }
    });
    const result = await this.dynamoClient.update({
      TableName: this.TABLE_NAME,
      Key: { PK: existing.PK, SK: existing.SK },
      UpdateExpression: `SET ${updateExpressions.join(", ")}`,
      ExpressionAttributeNames: expressionAttributeNames,
      ExpressionAttributeValues: expressionAttributeValues,
      ReturnValues: "ALL_NEW",
    });
    return {
      data: sanitizeItem((result.Attributes || {}) as Record<string, unknown>) as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }
}
