/**
 * Right Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RightEntity } from "@ddd/core/routing/models/index.js";
import { routingSchemas } from "@ddd/core/routing";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rou";

export function createRight(overrides: Partial<RightEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    assetId: overrides.assetId ?? faker.string.uuid(),
    status: overrides.status ?? "cleared",
    ...overrides,
  };

  return routingSchemas.RightsRecord.parse(raw);
}

export function rightBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRight(overrides));
}
