/**
 * Benefit DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Benefit DTOs
 *
 * DDD: Application DTOs for Benefit use cases.
 */

import type { GetBenefitRecordParams } from "@ddd/core/portfolio/types";

export type GetBenefitRecordInput = GetBenefitRecordParams;

export type GetBenefitRecordOutput = {};
