/**
 * EgressRecord DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EgressRecord DTOs
 *
 * DDD: Application DTOs for EgressRecord use cases.
 */

import type { ListEgressRecordsParams } from "@ddd/core/portfolio/types";

export type ListEgressRecordsInput = ListEgressRecordsParams;

export type ListEgressRecordsOutput = {};
