/**
 * Exposure DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Exposure DTOs
 *
 * DDD: Application DTOs for Exposure use cases.
 */

import type { GetExposureLedgerParams } from "@ddd/core/portfolio/types";

export type GetExposureLedgerInput = GetExposureLedgerParams;

export type GetExposureLedgerOutput = {};
