/**
 * Rescore DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Rescore DTOs
 *
 * DDD: Application DTOs for Rescore use cases.
 */

import type { RescoreRoadmapRequestInput } from "@ddd/core/portfolio/types";

export type RescoreRoadmapInput = RescoreRoadmapRequestInput;

export type RescoreRoadmapOutput = {};
