/**
 * Vendors DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Vendors Domain Module - Composition root
 *
 * DDD: Composition root for vendors domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EvaluationRepositoryAdapter,
  GoldenSetRepositoryAdapter,
  VendorCutoverRepositoryAdapter,
} from "@ddd/adapters/vendors";
import { getIdGeneratorService } from "@ddd/adapters";
import type { AdapterDynamoDBClient } from "@ddd/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListGoldenSets,
  ExecuteListVendorConnectors,
  ExecuteListVendorEvaluations,
  ExecuteRegisterVendorConnector,
  ExecuteStartVendorEvaluation,
} from "@ddd/services/vendors/usecases";
// Ports (interfaces)
import type {
  EvaluationRepository,
  GoldenSetRepository,
  VendorCutoverRepository,
} from "@ddd/services/vendors/ports";

export interface VendorsDomainModule {
  repos: {
    evaluations: EvaluationRepository;
    goldenSets: GoldenSetRepository;
    vendorCutovers: VendorCutoverRepository;
  };
  useCases: {
    evaluations: {
      create: ExecuteStartVendorEvaluation;
      list: ExecuteListVendorEvaluations;
    };
    goldenSets: {
      list: ExecuteListGoldenSets;
    };
  };
}

export function buildVendorsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): VendorsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      evaluations?: EvaluationRepository;
      goldenSets?: GoldenSetRepository;
      vendorCutovers?: VendorCutoverRepository;
    } = {};

    obj.evaluations = new EvaluationRepositoryAdapter(dynamoClient);
    obj.goldenSets = new GoldenSetRepositoryAdapter(dynamoClient);
    obj.vendorCutovers = new VendorCutoverRepositoryAdapter(dynamoClient);
    return {
      evaluations: obj.evaluations!,
      goldenSets: obj.goldenSets!,
      vendorCutovers: obj.vendorCutovers!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    evaluations: {
      create: new ExecuteStartVendorEvaluation(executionContext, idGenerator, repos.evaluations),
      list: new ExecuteListVendorEvaluations(executionContext, idGenerator, repos.evaluations),
    },
    goldenSets: {
      list: new ExecuteListGoldenSets(executionContext, idGenerator, repos.goldenSets),
    },
  };
  return { repos, useCases: useCases as VendorsDomainModule["useCases"] };
}
