/**
 * BenefitRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BenefitRepository Port
 *
 * DDD: Application port for benefitrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetBenefitRecordInput, GetBenefitRecordOutput } from "../dto/benefit.dto";
export interface BenefitRepository {
  getBenefitRecord(input: GetBenefitRecordInput): Promise<GetBenefitRecordOutput>;
}

export type { GetBenefitRecordInput, GetBenefitRecordOutput } from "../dto/benefit.dto";
