/**
 * EgressRecordRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EgressRecordRepository Port
 *
 * DDD: Application port for egressrecordrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListEgressRecordsInput, ListEgressRecordsOutput } from "../dto/egress-record.dto";
export interface EgressRecordRepository {
  listEgressRecords(input: ListEgressRecordsInput): Promise<ListEgressRecordsOutput>;
}

export type { ListEgressRecordsInput, ListEgressRecordsOutput } from "../dto/egress-record.dto";
