/**
 * ExposureRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExposureRepository Port
 *
 * DDD: Application port for exposurerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetExposureLedgerInput, GetExposureLedgerOutput } from "../dto/exposure.dto";
export interface ExposureRepository {
  getExposureLedger(input: GetExposureLedgerInput): Promise<GetExposureLedgerOutput>;
}

export type { GetExposureLedgerInput, GetExposureLedgerOutput } from "../dto/exposure.dto";
