/**
 * RescoreRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RescoreRepository Port
 *
 * DDD: Application port for rescorerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RescoreRoadmapInput, RescoreRoadmapOutput } from "../dto/rescore.dto";
export interface RescoreRepository {
  rescoreRoadmap(input: RescoreRoadmapInput): Promise<RescoreRoadmapOutput>;
}

export type { RescoreRoadmapInput, RescoreRoadmapOutput } from "../dto/rescore.dto";
