/**
 * RoadmapRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RoadmapRepository Port
 *
 * DDD: Application port for roadmaprepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListRoadmapEntriesInput, ListRoadmapEntriesOutput } from "../dto/roadmap.dto";
export interface RoadmapRepository {
  listRoadmapEntries(input: ListRoadmapEntriesInput): Promise<ListRoadmapEntriesOutput>;
}

export type { ListRoadmapEntriesInput, ListRoadmapEntriesOutput } from "../dto/roadmap.dto";
