/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vendor connectors */
        get: operations["listVendorConnectors"];
        put?: never;
        /** Register vendor connector */
        post: operations["registerVendorConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vendors/{vendorId}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendorId: string;
            };
            cookie?: never;
        };
        /** List vendor evaluations */
        get: operations["listVendorEvaluations"];
        put?: never;
        /**
         * Start vendor evaluation
         * @description Run a candidate vendor in shadow against the operation's own golden set and optionally against live queue traffic, without acting on the result.
         */
        post: operations["startVendorEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/queues/{queueId}/vendor-cutover": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                queueId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cut over vendor traffic
         * @description Move a queue to a different vendor or revert it to human-final decisioning, with a rollback window. Refused if the target vendor has no completed evaluation on this queue's golden set.
         */
        post: operations["cutoverVendorTraffic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/golden-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List golden sets
         * @description Labelled samples drawn from the operation's own queues.
         */
        get: operations["listGoldenSets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        VendorCapability: "ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image";
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        VendorId: string;
        /**
         * @description ISO 4217 currency code.
         * @example USD
         */
        Currency: string;
        /** @description Decimal-string amount + currency (never IEEE float). */
        Money: {
            /**
             * @description Signed decimal string with up to 5 fractional digits.
             * @example 1234.56
             */
            amount: string;
            /**
             * @description ISO 4217 currency code.
             * @example USD
             */
            currency: string;
        };
        VendorConnector: {
            id: string;
            name: string;
            /** @enum {string} */
            vendorClass?: "tech_giant" | "specialist_startup" | "in_house_build";
            capabilities: ("ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image")[];
            /** @enum {string} */
            status: "candidate" | "evaluating" | "live" | "fallback" | "suspended" | "retired";
            /** Format: float */
            contractedAccuracyFloor?: number;
            /** @description Decimal-string amount + currency (never IEEE float). */
            pricePerThousandCalls?: {
                /**
                 * @description Signed decimal string with up to 5 fractional digits.
                 * @example 1234.56
                 */
                amount: string;
                /**
                 * @description ISO 4217 currency code.
                 * @example USD
                 */
                currency: string;
            };
            permittedTerritories?: string[];
            processingTermsId?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        VendorConnectorListData: {
            items: {
                id: string;
                name: string;
                /** @enum {string} */
                vendorClass?: "tech_giant" | "specialist_startup" | "in_house_build";
                capabilities: ("ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image")[];
                /** @enum {string} */
                status: "candidate" | "evaluating" | "live" | "fallback" | "suspended" | "retired";
                /** Format: float */
                contractedAccuracyFloor?: number;
                /** @description Decimal-string amount + currency (never IEEE float). */
                pricePerThousandCalls?: {
                    /**
                     * @description Signed decimal string with up to 5 fractional digits.
                     * @example 1234.56
                     */
                    amount: string;
                    /**
                     * @description ISO 4217 currency code.
                     * @example USD
                     */
                    currency: string;
                };
                permittedTerritories?: string[];
                processingTermsId?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        VendorConnectorListResponse: {
            data: {
                items: {
                    id: string;
                    name: string;
                    /** @enum {string} */
                    vendorClass?: "tech_giant" | "specialist_startup" | "in_house_build";
                    capabilities: ("ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image")[];
                    /** @enum {string} */
                    status: "candidate" | "evaluating" | "live" | "fallback" | "suspended" | "retired";
                    /** Format: float */
                    contractedAccuracyFloor?: number;
                    /** @description Decimal-string amount + currency (never IEEE float). */
                    pricePerThousandCalls?: {
                        /**
                         * @description Signed decimal string with up to 5 fractional digits.
                         * @example 1234.56
                         */
                        amount: string;
                        /**
                         * @description ISO 4217 currency code.
                         * @example USD
                         */
                        currency: string;
                    };
                    permittedTerritories?: string[];
                    processingTermsId?: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        VendorConnectorCreate: {
            name: string;
            /** @enum {string} */
            vendorClass?: "tech_giant" | "specialist_startup" | "in_house_build";
            capabilities: ("ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image")[];
            /** Format: float */
            contractedAccuracyFloor?: number;
            /** @description Decimal-string amount + currency (never IEEE float). */
            pricePerThousandCalls?: {
                /**
                 * @description Signed decimal string with up to 5 fractional digits.
                 * @example 1234.56
                 */
                amount: string;
                /**
                 * @description ISO 4217 currency code.
                 * @example USD
                 */
                currency: string;
            };
            permittedTerritories?: string[];
            processingTermsId?: string;
        };
        VendorConnectorResponse: {
            data: {
                id: string;
                name: string;
                /** @enum {string} */
                vendorClass?: "tech_giant" | "specialist_startup" | "in_house_build";
                capabilities: ("ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image")[];
                /** @enum {string} */
                status: "candidate" | "evaluating" | "live" | "fallback" | "suspended" | "retired";
                /** Format: float */
                contractedAccuracyFloor?: number;
                /** @description Decimal-string amount + currency (never IEEE float). */
                pricePerThousandCalls?: {
                    /**
                     * @description Signed decimal string with up to 5 fractional digits.
                     * @example 1234.56
                     */
                    amount: string;
                    /**
                     * @description ISO 4217 currency code.
                     * @example USD
                     */
                    currency: string;
                };
                permittedTerritories?: string[];
                processingTermsId?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        EvaluationId: string;
        VendorEvaluation: {
            id: string;
            vendorId: string;
            queueId: string;
            goldenSetId?: string;
            /** @enum {string} */
            mode: "golden_set_only" | "live_shadow" | "golden_set_and_live_shadow";
            /** @enum {string} */
            status: "queued" | "running" | "complete" | "abandoned";
            /** Format: float */
            agreementWithHumanLabel?: number;
            /** Format: float */
            falseNegativeRate?: number;
            /** Format: float */
            falsePositiveRate?: number;
            residualHumanHandlingSeconds?: number;
            /** @description Decimal-string amount + currency (never IEEE float). */
            totalCostPerThousandDecisions?: {
                /**
                 * @description Signed decimal string with up to 5 fractional digits.
                 * @example 1234.56
                 */
                amount: string;
                /**
                 * @description ISO 4217 currency code.
                 * @example USD
                 */
                currency: string;
            };
            meetsContractedFloor?: boolean;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        VendorEvaluationListData: {
            items: {
                id: string;
                vendorId: string;
                queueId: string;
                goldenSetId?: string;
                /** @enum {string} */
                mode: "golden_set_only" | "live_shadow" | "golden_set_and_live_shadow";
                /** @enum {string} */
                status: "queued" | "running" | "complete" | "abandoned";
                /** Format: float */
                agreementWithHumanLabel?: number;
                /** Format: float */
                falseNegativeRate?: number;
                /** Format: float */
                falsePositiveRate?: number;
                residualHumanHandlingSeconds?: number;
                /** @description Decimal-string amount + currency (never IEEE float). */
                totalCostPerThousandDecisions?: {
                    /**
                     * @description Signed decimal string with up to 5 fractional digits.
                     * @example 1234.56
                     */
                    amount: string;
                    /**
                     * @description ISO 4217 currency code.
                     * @example USD
                     */
                    currency: string;
                };
                meetsContractedFloor?: boolean;
                /** Format: date-time */
                completedAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor?: string;
        };
        VendorEvaluationListResponse: {
            data: {
                items: {
                    id: string;
                    vendorId: string;
                    queueId: string;
                    goldenSetId?: string;
                    /** @enum {string} */
                    mode: "golden_set_only" | "live_shadow" | "golden_set_and_live_shadow";
                    /** @enum {string} */
                    status: "queued" | "running" | "complete" | "abandoned";
                    /** Format: float */
                    agreementWithHumanLabel?: number;
                    /** Format: float */
                    falseNegativeRate?: number;
                    /** Format: float */
                    falsePositiveRate?: number;
                    residualHumanHandlingSeconds?: number;
                    /** @description Decimal-string amount + currency (never IEEE float). */
                    totalCostPerThousandDecisions?: {
                        /**
                         * @description Signed decimal string with up to 5 fractional digits.
                         * @example 1234.56
                         */
                        amount: string;
                        /**
                         * @description ISO 4217 currency code.
                         * @example USD
                         */
                        currency: string;
                    };
                    meetsContractedFloor?: boolean;
                    /** Format: date-time */
                    completedAt?: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        VendorEvaluationCreate: {
            queueId: string;
            goldenSetId?: string;
            /** @enum {string} */
            mode: "golden_set_only" | "live_shadow" | "golden_set_and_live_shadow";
            sampleSize?: number;
        };
        VendorEvaluationResponse: {
            data: {
                id: string;
                vendorId: string;
                queueId: string;
                goldenSetId?: string;
                /** @enum {string} */
                mode: "golden_set_only" | "live_shadow" | "golden_set_and_live_shadow";
                /** @enum {string} */
                status: "queued" | "running" | "complete" | "abandoned";
                /** Format: float */
                agreementWithHumanLabel?: number;
                /** Format: float */
                falseNegativeRate?: number;
                /** Format: float */
                falsePositiveRate?: number;
                residualHumanHandlingSeconds?: number;
                /** @description Decimal-string amount + currency (never IEEE float). */
                totalCostPerThousandDecisions?: {
                    /**
                     * @description Signed decimal string with up to 5 fractional digits.
                     * @example 1234.56
                     */
                    amount: string;
                    /**
                     * @description ISO 4217 currency code.
                     * @example USD
                     */
                    currency: string;
                };
                meetsContractedFloor?: boolean;
                /** Format: date-time */
                completedAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        VendorCutoverRequest: {
            /** @description Use the literal value human_only to revert to human-final decisioning */
            targetVendorId: string;
            /** @enum {string} */
            reason: "accuracy_drift" | "cost" | "coverage_gap" | "contract_end" | "incident" | "planned_migration";
            /** @default 120 */
            rollbackWindowMinutes: number;
        };
        QueueCutoverResult: {
            queueId: string;
            activeVendorId: string;
            fallbackVendorId: string;
            rollbackWindowMinutes?: number;
        };
        QueueCutoverResponse: {
            data: {
                queueId: string;
                activeVendorId: string;
                fallbackVendorId: string;
                rollbackWindowMinutes?: number;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        GoldenSetId: string;
        GoldenSet: {
            id: string;
            queueId: string;
            itemCount: number;
            labelledBy?: string[];
            /** Format: float */
            interAnnotatorAgreement?: number;
            policyDefinitionVersion?: string;
            restrictedStore?: boolean;
            /** Format: date-time */
            refreshedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GoldenSetListData: {
            items: {
                id: string;
                queueId: string;
                itemCount: number;
                labelledBy?: string[];
                /** Format: float */
                interAnnotatorAgreement?: number;
                policyDefinitionVersion?: string;
                restrictedStore?: boolean;
                /** Format: date-time */
                refreshedAt?: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
            }[];
            nextCursor?: string;
        };
        GoldenSetListResponse: {
            data: {
                items: {
                    id: string;
                    queueId: string;
                    itemCount: number;
                    labelledBy?: string[];
                    /** Format: float */
                    interAnnotatorAgreement?: number;
                    policyDefinitionVersion?: string;
                    restrictedStore?: boolean;
                    /** Format: date-time */
                    refreshedAt?: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                }[];
                nextCursor?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque cursor for keyset pagination. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listVendorConnectors: {
        parameters: {
            query?: {
                /** @description Opaque cursor for keyset pagination. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                capability?: "ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vendor connectors page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                name: string;
                                /** @enum {string} */
                                vendorClass?: "tech_giant" | "specialist_startup" | "in_house_build";
                                capabilities: ("ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image")[];
                                /** @enum {string} */
                                status: "candidate" | "evaluating" | "live" | "fallback" | "suspended" | "retired";
                                /** Format: float */
                                contractedAccuracyFloor?: number;
                                /** @description Decimal-string amount + currency (never IEEE float). */
                                pricePerThousandCalls?: {
                                    /**
                                     * @description Signed decimal string with up to 5 fractional digits.
                                     * @example 1234.56
                                     */
                                    amount: string;
                                    /**
                                     * @description ISO 4217 currency code.
                                     * @example USD
                                     */
                                    currency: string;
                                };
                                permittedTerritories?: string[];
                                processingTermsId?: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    registerVendorConnector: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    vendorClass?: "tech_giant" | "specialist_startup" | "in_house_build";
                    capabilities: ("ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image")[];
                    /** Format: float */
                    contractedAccuracyFloor?: number;
                    /** @description Decimal-string amount + currency (never IEEE float). */
                    pricePerThousandCalls?: {
                        /**
                         * @description Signed decimal string with up to 5 fractional digits.
                         * @example 1234.56
                         */
                        amount: string;
                        /**
                         * @description ISO 4217 currency code.
                         * @example USD
                         */
                        currency: string;
                    };
                    permittedTerritories?: string[];
                    processingTermsId?: string;
                };
            };
        };
        responses: {
            /** @description Vendor connector registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            name: string;
                            /** @enum {string} */
                            vendorClass?: "tech_giant" | "specialist_startup" | "in_house_build";
                            capabilities: ("ingest_metadata" | "ingest_text" | "moderation_text" | "moderation_image" | "moderation_video" | "tagging_image" | "tagging_video" | "custom_training_text" | "custom_training_image")[];
                            /** @enum {string} */
                            status: "candidate" | "evaluating" | "live" | "fallback" | "suspended" | "retired";
                            /** Format: float */
                            contractedAccuracyFloor?: number;
                            /** @description Decimal-string amount + currency (never IEEE float). */
                            pricePerThousandCalls?: {
                                /**
                                 * @description Signed decimal string with up to 5 fractional digits.
                                 * @example 1234.56
                                 */
                                amount: string;
                                /**
                                 * @description ISO 4217 currency code.
                                 * @example USD
                                 */
                                currency: string;
                            };
                            permittedTerritories?: string[];
                            processingTermsId?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listVendorEvaluations: {
        parameters: {
            query?: {
                /** @description Opaque cursor for keyset pagination. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
            };
            header?: never;
            path: {
                vendorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluations page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                vendorId: string;
                                queueId: string;
                                goldenSetId?: string;
                                /** @enum {string} */
                                mode: "golden_set_only" | "live_shadow" | "golden_set_and_live_shadow";
                                /** @enum {string} */
                                status: "queued" | "running" | "complete" | "abandoned";
                                /** Format: float */
                                agreementWithHumanLabel?: number;
                                /** Format: float */
                                falseNegativeRate?: number;
                                /** Format: float */
                                falsePositiveRate?: number;
                                residualHumanHandlingSeconds?: number;
                                /** @description Decimal-string amount + currency (never IEEE float). */
                                totalCostPerThousandDecisions?: {
                                    /**
                                     * @description Signed decimal string with up to 5 fractional digits.
                                     * @example 1234.56
                                     */
                                    amount: string;
                                    /**
                                     * @description ISO 4217 currency code.
                                     * @example USD
                                     */
                                    currency: string;
                                };
                                meetsContractedFloor?: boolean;
                                /** Format: date-time */
                                completedAt?: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    startVendorEvaluation: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                vendorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    queueId: string;
                    goldenSetId?: string;
                    /** @enum {string} */
                    mode: "golden_set_only" | "live_shadow" | "golden_set_and_live_shadow";
                    sampleSize?: number;
                };
            };
        };
        responses: {
            /** @description Shadow evaluation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            vendorId: string;
                            queueId: string;
                            goldenSetId?: string;
                            /** @enum {string} */
                            mode: "golden_set_only" | "live_shadow" | "golden_set_and_live_shadow";
                            /** @enum {string} */
                            status: "queued" | "running" | "complete" | "abandoned";
                            /** Format: float */
                            agreementWithHumanLabel?: number;
                            /** Format: float */
                            falseNegativeRate?: number;
                            /** Format: float */
                            falsePositiveRate?: number;
                            residualHumanHandlingSeconds?: number;
                            /** @description Decimal-string amount + currency (never IEEE float). */
                            totalCostPerThousandDecisions?: {
                                /**
                                 * @description Signed decimal string with up to 5 fractional digits.
                                 * @example 1234.56
                                 */
                                amount: string;
                                /**
                                 * @description ISO 4217 currency code.
                                 * @example USD
                                 */
                                currency: string;
                            };
                            meetsContractedFloor?: boolean;
                            /** Format: date-time */
                            completedAt?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    cutoverVendorTraffic: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                queueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Use the literal value human_only to revert to human-final decisioning */
                    targetVendorId: string;
                    /** @enum {string} */
                    reason: "accuracy_drift" | "cost" | "coverage_gap" | "contract_end" | "incident" | "planned_migration";
                    /** @default 120 */
                    rollbackWindowMinutes?: number;
                };
            };
        };
        responses: {
            /** @description Cutover accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            queueId: string;
                            activeVendorId: string;
                            fallbackVendorId: string;
                            rollbackWindowMinutes?: number;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listGoldenSets: {
        parameters: {
            query?: {
                /** @description Opaque cursor for keyset pagination. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
                queueId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Golden sets page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                queueId: string;
                                itemCount: number;
                                labelledBy?: string[];
                                /** Format: float */
                                interAnnotatorAgreement?: number;
                                policyDefinitionVersion?: string;
                                restrictedStore?: boolean;
                                /** Format: date-time */
                                refreshedAt?: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
