/**
 * ListEgressRecords handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listEgressRecords } from "@ddd/api-server/domains/portfolio/handlers";
import type { PortfolioDDDDependencies } from "@ddd/api-server/domains/portfolio";
import { createEgressRecord as createEgressRecordEntity } from "@ddd/factories/portfolio";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ddd/tests/shared";
import { PORTFOLIO_USE_CASES } from "../__factories__/use-cases.js";

describe("ListEgressRecords", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PortfolioDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PortfolioDDDDependencies>(
      PORTFOLIO_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createEgressRecordEntity({ orgId }),
      createEgressRecordEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListEgressRecords, "execute").mockResolvedValue(useCaseResult);

    await listEgressRecords(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListEgressRecords.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
