/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildPortfolioDomainModule } from "./portfolio/dependencies/portfolio-ddd.dependencies.js";
export { buildQueuesDomainModule } from "./queues/dependencies/queues-ddd.dependencies.js";
export { buildRoutingDomainModule } from "./routing/dependencies/routing-ddd.dependencies.js";
export { buildVendorsDomainModule } from "./vendors/dependencies/vendors-ddd.dependencies.js";

// Export all domain dependency types
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { PortfolioDomainModule } from "./portfolio/dependencies/portfolio-ddd.dependencies.js";
export type { QueuesDomainModule } from "./queues/dependencies/queues-ddd.dependencies.js";
export type { RoutingDomainModule } from "./routing/dependencies/routing-ddd.dependencies.js";
export type { VendorsDomainModule } from "./vendors/dependencies/vendors-ddd.dependencies.js";
