/**
 * AppealRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AppealRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AppealRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AppealRepository,
} from "@ddd/services/routing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AppealRepositoryDdb } from "./appeal-repository.ddb.js";

/**
 * AppealRepositoryAdapter
 *
 * Implements AppealRepository port for infrastructure layer.
 */
export class AppealRepositoryAdapter implements AppealRepository {
  private readonly ddb: AppealRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AppealRepositoryDdb(this.dynamoClient);
  }

  async listAppeals(input: Parameters<AppealRepository['listAppeals']>[0]): Promise<Awaited<ReturnType<AppealRepository['listAppeals']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAppeals(input);
  }

  async openAppeal(input: Parameters<AppealRepository['openAppeal']>[0]): Promise<Awaited<ReturnType<AppealRepository['openAppeal']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openAppeal(input);
  }
}
