/**
 * CalibrationSampleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CalibrationSampleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CalibrationSampleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CalibrationSampleRepository,
} from "@ddd/services/routing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CalibrationSampleRepositoryDdb } from "./calibration-sample-repository.ddb.js";

/**
 * CalibrationSampleRepositoryAdapter
 *
 * Implements CalibrationSampleRepository port for infrastructure layer.
 */
export class CalibrationSampleRepositoryAdapter implements CalibrationSampleRepository {
  private readonly ddb: CalibrationSampleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CalibrationSampleRepositoryDdb(this.dynamoClient);
  }

  async listCalibrationSamples(input: Parameters<CalibrationSampleRepository['listCalibrationSamples']>[0]): Promise<Awaited<ReturnType<CalibrationSampleRepository['listCalibrationSamples']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCalibrationSamples(input);
  }
}
