/**
 * PreemptRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PreemptRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PreemptRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PreemptRepository,
} from "@ddd/services/routing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PreemptRepositoryDdb } from "./preempt-repository.ddb.js";

/**
 * PreemptRepositoryAdapter
 *
 * Implements PreemptRepository port for infrastructure layer.
 */
export class PreemptRepositoryAdapter implements PreemptRepository {
  private readonly ddb: PreemptRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PreemptRepositoryDdb(this.dynamoClient);
  }

  async preemptResponseClock(input: Parameters<PreemptRepository['preemptResponseClock']>[0]): Promise<Awaited<ReturnType<PreemptRepository['preemptResponseClock']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.preemptResponseClock(input);
  }
}
