/**
 * RightRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RightRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RightRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RightRepository,
} from "@ddd/services/routing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RightRepositoryDdb } from "./right-repository.ddb.js";

/**
 * RightRepositoryAdapter
 *
 * Implements RightRepository port for infrastructure layer.
 */
export class RightRepositoryAdapter implements RightRepository {
  private readonly ddb: RightRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RightRepositoryDdb(this.dynamoClient);
  }

  async getRightsRecord(input: Parameters<RightRepository['getRightsRecord']>[0]): Promise<Awaited<ReturnType<RightRepository['getRightsRecord']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRightsRecord(input);
  }
}
