/**
 * WorkItemRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WorkItemRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements WorkItemRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  WorkItemRepository,
} from "@ddd/services/routing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { WorkItemRepositoryDdb } from "./work-item-repository.ddb.js";

/**
 * WorkItemRepositoryAdapter
 *
 * Implements WorkItemRepository port for infrastructure layer.
 */
export class WorkItemRepositoryAdapter implements WorkItemRepository {
  private readonly ddb: WorkItemRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new WorkItemRepositoryDdb(this.dynamoClient);
  }

  async listWorkItems(input: Parameters<WorkItemRepository['listWorkItems']>[0]): Promise<Awaited<ReturnType<WorkItemRepository['listWorkItems']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listWorkItems(input);
  }

  async submitWorkItem(input: Parameters<WorkItemRepository['submitWorkItem']>[0]): Promise<Awaited<ReturnType<WorkItemRepository['submitWorkItem']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitWorkItem(input);
  }
}
