/**
 * SetThresholdPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { setThresholdPolicy } from "@ddd/api-server/domains/queues/handlers";
import type { QueuesDDDDependencies } from "@ddd/api-server/domains/queues";
import { createThresholdPolicy as createThresholdPolicyEntity } from "@ddd/factories/queues";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ddd/tests/shared";
import { QUEUES_USE_CASES } from "../__factories__/use-cases.js";

describe("SetThresholdPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: QueuesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<QueuesDDDDependencies>(
      QUEUES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createThresholdPolicyEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { queueId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSetThresholdPolicy, "execute").mockResolvedValue(useCaseResult);

    await setThresholdPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSetThresholdPolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ queueId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
