/**
 * GoldenSetRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GoldenSetRepository Port
 *
 * DDD: Application port for goldensetrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListGoldenSetsInput, ListGoldenSetsOutput } from "../dto/golden-set.dto";
export interface GoldenSetRepository {
  listGoldenSets(input: ListGoldenSetsInput): Promise<ListGoldenSetsOutput>;
}

export type { ListGoldenSetsInput, ListGoldenSetsOutput } from "../dto/golden-set.dto";
