/**
 * VendorCutoverRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VendorCutoverRepository Port
 *
 * DDD: Application port for vendorcutoverrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CutoverVendorTrafficInput, CutoverVendorTrafficOutput } from "../dto/vendor-cutover.dto";
export interface VendorCutoverRepository {
  cutoverVendorTraffic(input: CutoverVendorTrafficInput): Promise<CutoverVendorTrafficOutput>;
}

export type { CutoverVendorTrafficInput, CutoverVendorTrafficOutput } from "../dto/vendor-cutover.dto";
