/**
 * Routes for AutomationApproval
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { decideAutomationApproval } from "../handlers/automation-approval.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function automationApprovalRoutes(fastify: FastifyInstance) {
  // POST /v1/governance/queues/{queueId}/automation-approval (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/governance/queues/:queueId/automation-approval",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { queueId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getQueuesDependenciesForRequest();
        await decideAutomationApproval(request, reply, deps);
      });
    }
  );


}
