/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { automationApprovalRoutes } from "./automation-approval.routes.js";
export { policyDefinitionRoutes } from "./policy-definition.routes.js";
export { queueRoutes } from "./queue.routes.js";
export { scorecardRoutes } from "./scorecard.routes.js";
export { thresholdPolicyRoutes } from "./threshold-policy.routes.js";
