/**
 * Routes for Queue
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getQueue, listQueues, registerQueue } from "../handlers/queue.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function queueRoutes(fastify: FastifyInstance) {
  // GET /v1/queues (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/queues",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getQueuesDependenciesForRequest();
        await listQueues(request, reply, deps);
      });
    }
  );


  // POST /v1/queues (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/queues",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getQueuesDependenciesForRequest();
        await registerQueue(request, reply, deps);
      });
    }
  );


  // GET /v1/queues/{queueId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/queues/:queueId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { queueId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getQueuesDependenciesForRequest();
        await getQueue(request, reply, deps);
      });
    }
  );


}
