/**
 * GetExposureLedger handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getExposureLedger } from "@ddd/api-server/domains/portfolio/handlers";
import type { PortfolioDDDDependencies } from "@ddd/api-server/domains/portfolio";
import { createExposure as createExposureEntity } from "@ddd/factories/portfolio";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ddd/tests/shared";
import { PORTFOLIO_USE_CASES } from "../__factories__/use-cases.js";

describe("GetExposureLedger", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PortfolioDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PortfolioDDDDependencies>(
      PORTFOLIO_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createExposureEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetExposureLedger, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { agentId: entity.id };

    await getExposureLedger(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetExposureLedger.execute).toHaveBeenCalledWith(expect.objectContaining({ agentId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { agentId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetExposureLedger, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getExposureLedger(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
