/**
 * AppealRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AppealRepository Port
 *
 * DDD: Application port for appealrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListAppealsInput, ListAppealsOutput, OpenAppealInput, OpenAppealOutput } from "../dto/appeal.dto";
export interface AppealRepository {
  listAppeals(input: ListAppealsInput): Promise<ListAppealsOutput>;
  openAppeal(input: OpenAppealInput): Promise<OpenAppealOutput>;
}

export type { ListAppealsInput, ListAppealsOutput, OpenAppealInput, OpenAppealOutput } from "../dto/appeal.dto";
