/**
 * CalibrationSampleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CalibrationSampleRepository Port
 *
 * DDD: Application port for calibrationsamplerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListCalibrationSamplesInput, ListCalibrationSamplesOutput } from "../dto/calibration-sample.dto";
export interface CalibrationSampleRepository {
  listCalibrationSamples(input: ListCalibrationSamplesInput): Promise<ListCalibrationSamplesOutput>;
}

export type { ListCalibrationSamplesInput, ListCalibrationSamplesOutput } from "../dto/calibration-sample.dto";
