/**
 * PreemptRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PreemptRepository Port
 *
 * DDD: Application port for preemptrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PreemptResponseClockInput, PreemptResponseClockOutput } from "../dto/preempt.dto";
export interface PreemptRepository {
  preemptResponseClock(input: PreemptResponseClockInput): Promise<PreemptResponseClockOutput>;
}

export type { PreemptResponseClockInput, PreemptResponseClockOutput } from "../dto/preempt.dto";
