/**
 * ResolutionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResolutionRepository Port
 *
 * DDD: Application port for resolutionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ResolveAppealInput, ResolveAppealOutput } from "../dto/resolution.dto";
export interface ResolutionRepository {
  resolveAppeal(input: ResolveAppealInput): Promise<ResolveAppealOutput>;
}

export type { ResolveAppealInput, ResolveAppealOutput } from "../dto/resolution.dto";
