/**
 * ResponseClockRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResponseClockRepository Port
 *
 * DDD: Application port for responseclockrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListResponseClocksInput, ListResponseClocksOutput } from "../dto/response-clock.dto";
export interface ResponseClockRepository {
  listResponseClocks(input: ListResponseClocksInput): Promise<ListResponseClocksOutput>;
}

export type { ListResponseClocksInput, ListResponseClocksOutput } from "../dto/response-clock.dto";
