/**
 * ReviewRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReviewRepository Port
 *
 * DDD: Application port for reviewrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RecordHumanReviewInput, RecordHumanReviewOutput } from "../dto/review.dto";
export interface ReviewRepository {
  recordHumanReview(input: RecordHumanReviewInput): Promise<RecordHumanReviewOutput>;
}

export type { RecordHumanReviewInput, RecordHumanReviewOutput } from "../dto/review.dto";
