/**
 * RightRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RightRepository Port
 *
 * DDD: Application port for rightrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetRightsRecordInput, GetRightsRecordOutput } from "../dto/right.dto";
export interface RightRepository {
  getRightsRecord(input: GetRightsRecordInput): Promise<GetRightsRecordOutput>;
}

export type { GetRightsRecordInput, GetRightsRecordOutput } from "../dto/right.dto";
