/**
 * WorkItemRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WorkItemRepository Port
 *
 * DDD: Application port for workitemrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListWorkItemsInput, ListWorkItemsOutput, SubmitWorkItemInput, SubmitWorkItemOutput } from "../dto/work-item.dto";
export interface WorkItemRepository {
  listWorkItems(input: ListWorkItemsInput): Promise<ListWorkItemsOutput>;
  submitWorkItem(input: SubmitWorkItemInput): Promise<SubmitWorkItemOutput>;
}

export type { ListWorkItemsInput, ListWorkItemsOutput, SubmitWorkItemInput, SubmitWorkItemOutput } from "../dto/work-item.dto";
