/**
 * GetQueue handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getQueue } from "@ddd/api-server/domains/queues/handlers";
import type { QueuesDDDDependencies } from "@ddd/api-server/domains/queues";
import { createQueue as createQueueEntity } from "@ddd/factories/queues";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ddd/tests/shared";
import { QUEUES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetQueue", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: QueuesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<QueuesDDDDependencies>(
      QUEUES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createQueueEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetQueue, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { queueId: entity.id };

    await getQueue(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetQueue.execute).toHaveBeenCalledWith(expect.objectContaining({ queueId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { queueId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetQueue, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getQueue(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
