/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@ddd/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@ddd/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@ddd/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _identity from "./identity/index.js";
import * as _portfolio from "./portfolio/index.js";
import * as _queues from "./queues/index.js";
import * as _routing from "./routing/index.js";
import * as _vendors from "./vendors/index.js";

// Export as namespaces
export const identity = _identity;
export const portfolio = _portfolio;
export const queues = _queues;
export const routing = _routing;
export const vendors = _vendors;
