/**
 * Appeal DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Appeal DTOs
 *
 * DDD: Application DTOs for Appeal use cases.
 */

import type { ListAppealsParams, OpenAppealRequestInput } from "@ddd/core/routing/types";

export type ListAppealsInput = ListAppealsParams;

export type OpenAppealInput = OpenAppealRequestInput;

export type ListAppealsOutput = {};

export type OpenAppealOutput = {};
