/**
 * CalibrationSample DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CalibrationSample DTOs
 *
 * DDD: Application DTOs for CalibrationSample use cases.
 */

import type { ListCalibrationSamplesParams } from "@ddd/core/routing/types";

export type ListCalibrationSamplesInput = ListCalibrationSamplesParams;

export type ListCalibrationSamplesOutput = {};
