/**
 * Preempt DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Preempt DTOs
 *
 * DDD: Application DTOs for Preempt use cases.
 */

import type { PreemptResponseClockParams } from "@ddd/core/routing/types";

export type PreemptResponseClockInput = PreemptResponseClockParams;

export type PreemptResponseClockOutput = {};
