/**
 * ResponseClock DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ResponseClock DTOs
 *
 * DDD: Application DTOs for ResponseClock use cases.
 */

import type { ListResponseClocksParams } from "@ddd/core/routing/types";

export type ListResponseClocksInput = ListResponseClocksParams;

export type ListResponseClocksOutput = {};
