/**
 * Review DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Review DTOs
 *
 * DDD: Application DTOs for Review use cases.
 */

import type { RecordHumanReviewParams, RecordHumanReviewRequestInput } from "@ddd/core/routing/types";

export type RecordHumanReviewInput = RecordHumanReviewParams & RecordHumanReviewRequestInput;

export type RecordHumanReviewOutput = {};
