/**
 * Right DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Right DTOs
 *
 * DDD: Application DTOs for Right use cases.
 */

import type { GetRightsRecordParams } from "@ddd/core/routing/types";

export type GetRightsRecordInput = GetRightsRecordParams;

export type GetRightsRecordOutput = {};
