/**
 * Routing DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Routing DTOs
 *
 * DDD: Application DTOs for Routing use cases.
 */

import type { GetRoutingDecisionParams } from "@ddd/core/routing/types";

export type GetRoutingDecisionInput = GetRoutingDecisionParams;

export type GetRoutingDecisionOutput = {};
