/**
 * WorkItem DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WorkItem DTOs
 *
 * DDD: Application DTOs for WorkItem use cases.
 */

import type { ListWorkItemsParams, SubmitWorkItemRequestInput } from "@ddd/core/routing/types";

export type ListWorkItemsInput = ListWorkItemsParams;

export type SubmitWorkItemInput = SubmitWorkItemRequestInput;

export type ListWorkItemsOutput = {};

export type SubmitWorkItemOutput = {};
