/**
 * Handlers for EgressRecord
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PortfolioDomainModule } from "../dependencies/portfolio-ddd.dependencies.js";
import type { ListEgressRecordsInput } from "@ddd/services/portfolio";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/governance/egress-records
 * Operation: listEgressRecords
 */
export async function listEgressRecords(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], queueId?: string | string[], vendorId?: string | string[], period?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PortfolioDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEgressRecordsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.egressRecords.list.execute(input);
  return reply.code(200).send(result);
}


