/**
 * Handlers for Rescore
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PortfolioDomainModule } from "../dependencies/portfolio-ddd.dependencies.js";
import type { RescoreRoadmapInput } from "@ddd/services/portfolio";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/roadmap/rescore
 * Operation: rescoreRoadmap
 */
export async function rescoreRoadmap(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PortfolioDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RescoreRoadmapInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.rescores.get.execute(input);
  return reply.code(200).send(result);
}


