/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the queues domain.
 * Use these factories in tests to create test data.
 */

export { createAutomationApproval } from "./automation-approval/entity/automation-approval.entity.factory.js";
export { createPolicyDefinition } from "./policy-definition/entity/policy-definition.entity.factory.js";
export { createQueue } from "./queue/entity/queue.entity.factory.js";
export { createScorecard } from "./scorecard/entity/scorecard.entity.factory.js";
export { createThresholdPolicy } from "./threshold-policy/entity/threshold-policy.entity.factory.js";
