/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the routing domain.
 * Use these factories in tests to create test data.
 */

export { createAppeal } from "./appeal/entity/appeal.entity.factory.js";
export { createCreatePreemptRequest } from "./preempt/dto/create-preempt.dto.factory.js";
export { createPreempt } from "./preempt/entity/preempt.entity.factory.js";
export { createResolution } from "./resolution/entity/resolution.entity.factory.js";
export { createResponseClock } from "./response-clock/entity/response-clock.entity.factory.js";
export { createReview } from "./review/entity/review.entity.factory.js";
export { createRight } from "./right/entity/right.entity.factory.js";
export { createRouting } from "./routing/entity/routing.entity.factory.js";
export { createWorkItem } from "./work-item/entity/work-item.entity.factory.js";
