/**
 * ExecuteListRoadmapEntries - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRoadmapEntries Use Case
 *
 * DDD: Application use case for list Roadmap.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRoadmapEntriesInput, ListRoadmapEntriesOutput } from "../dto/roadmap.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { RoadmapRepository } from "../ports";

export class ExecuteListRoadmapEntries {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly roadmap: RoadmapRepository
  ) {}

  async execute(input: ListRoadmapEntriesInput): Promise<ListRoadmapEntriesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pflId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.roadmap.listRoadmapEntries({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRoadmapEntriesOutput;
  }
}
