/**
 * ExecuteListEgressRecords - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEgressRecords Use Case
 *
 * DDD: Application use case for list EgressRecord.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEgressRecordsInput, ListEgressRecordsOutput } from "../dto/egress-record.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { EgressRecordRepository } from "../ports";

export class ExecuteListEgressRecords {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly egressRecord: EgressRecordRepository
  ) {}

  async execute(input: ListEgressRecordsInput): Promise<ListEgressRecordsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pflId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.egressRecord.listEgressRecords({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEgressRecordsOutput;
  }
}
