/**
 * ExecuteGetBenefitRecord - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBenefitRecord Use Case
 *
 * DDD: Application use case for get Benefit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBenefitRecordInput, GetBenefitRecordOutput } from "../dto/benefit.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { BenefitRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetBenefitRecord {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly benefit: BenefitRepository
  ) {}

  async execute(input: GetBenefitRecordInput): Promise<GetBenefitRecordOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pflId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).queueId) {
      throw new ValidationError("queueId is required");
    }
    const queueId = (input as any).queueId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.benefit.getBenefitRecord({ queueId: queueId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${queueId}`);
    }

    return entity as GetBenefitRecordOutput;
  }
}
