/**
 * ExecuteGetExposureLedger - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetExposureLedger Use Case
 *
 * DDD: Application use case for get Exposure.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetExposureLedgerInput, GetExposureLedgerOutput } from "../dto/exposure.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ddd/services/_shared/index.js";
import type { ExposureRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetExposureLedger {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exposure: ExposureRepository
  ) {}

  async execute(input: GetExposureLedgerInput): Promise<GetExposureLedgerOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pflId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).agentId) {
      throw new ValidationError("agentId is required");
    }
    const agentId = (input as any).agentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.exposure.getExposureLedger({ agentId: agentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${agentId}`);
    }

    return entity as GetExposureLedgerOutput;
  }
}
