/**
 * Routes for Benefit
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getBenefitRecord } from "../handlers/benefit.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function benefitRoutes(fastify: FastifyInstance) {
  // GET /v1/queues/{queueId}/benefit (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/queues/:queueId/benefit",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { queueId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPortfolioDependenciesForRequest();
        await getBenefitRecord(request, reply, deps);
      });
    }
  );


}
