/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the portfolio domain.
 * Use these factories in tests to create test data.
 */

export { createBenefit } from "./benefit/entity/benefit.entity.factory.js";
export { createEgressRecord } from "./egress-record/entity/egress-record.entity.factory.js";
export { createExposure } from "./exposure/entity/exposure.entity.factory.js";
export { createRoadmap } from "./roadmap/entity/roadmap.entity.factory.js";
