/**
 * GetExposure DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetExposureLedgerParams } from "@ddd/core/portfolio";

export function createGetExposureRequest(overrides: Partial<GetExposureLedgerParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
