/**
 * EgressRecord Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { EgressRecordEntity } from "@ddd/core/portfolio/models/index.js";
import { portfolioSchemas } from "@ddd/core/portfolio";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pfl";

export function createEgressRecord(overrides: Partial<EgressRecordEntity> = {}) {
  const raw = {
    id: overrides.id ?? `egr_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    sentAt: overrides.sentAt ?? new Date().toISOString(),
    vendorId: overrides.vendorId ?? faker.string.uuid(),
    workItemId: overrides.workItemId ?? faker.string.uuid(),
    ...overrides,
  };

  return portfolioSchemas.EgressRecord.parse(raw);
}

export function egressRecordBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEgressRecord(overrides));
}
