/**
 * PreemptResponseClock handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { preemptResponseClock } from "@ddd/api-server/domains/routing/handlers";
import type { RoutingDDDDependencies } from "@ddd/api-server/domains/routing";
import { createPreempt as createPreemptEntity } from "@ddd/factories/routing";
import { createCreatePreemptRequest } from "@ddd/factories/routing";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ddd/tests/shared";
import { ROUTING_USE_CASES } from "../__factories__/use-cases.js";

describe("PreemptResponseClock", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RoutingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RoutingDDDDependencies>(
      ROUTING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreatePreemptRequest();
    const entity = createPreemptEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePreemptResponseClock, "execute").mockResolvedValue(useCaseResult);

    await preemptResponseClock(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePreemptResponseClock.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
