/**
 * AutomationApproval DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AutomationApproval DTOs
 *
 * DDD: Application DTOs for AutomationApproval use cases.
 */

import type { DecideAutomationApprovalParams, DecideAutomationApprovalRequestInput } from "@ddd/core/queues/types";

export type DecideAutomationApprovalInput = DecideAutomationApprovalParams & DecideAutomationApprovalRequestInput;

export type DecideAutomationApprovalOutput = {};
