/**
 * PolicyDefinition DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyDefinition DTOs
 *
 * DDD: Application DTOs for PolicyDefinition use cases.
 */

import type { PinPolicyDefinitionParams, PinPolicyDefinitionRequestInput } from "@ddd/core/queues/types";

export type PinPolicyDefinitionInput = PinPolicyDefinitionParams & PinPolicyDefinitionRequestInput;

export type PinPolicyDefinitionOutput = {};
