/**
 * Queue DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Queue DTOs
 *
 * DDD: Application DTOs for Queue use cases.
 */

import type { GetQueueParams, ListQueuesParams, RegisterQueueRequestInput } from "@ddd/core/queues/types";

export type ListQueuesInput = ListQueuesParams;

export type RegisterQueueInput = RegisterQueueRequestInput;

export type GetQueueInput = GetQueueParams;

export type ListQueuesOutput = {};

export type RegisterQueueOutput = {};

export type GetQueueOutput = {};
