/**
 * ThresholdPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ThresholdPolicy DTOs
 *
 * DDD: Application DTOs for ThresholdPolicy use cases.
 */

import type { GetThresholdPolicyParams, SetThresholdPolicyParams, SetThresholdPolicyRequestInput } from "@ddd/core/queues/types";

export type GetThresholdPolicyInput = GetThresholdPolicyParams;

export type SetThresholdPolicyInput = SetThresholdPolicyParams & SetThresholdPolicyRequestInput;

export type GetThresholdPolicyOutput = {};

export type SetThresholdPolicyOutput = {};
