/**
 * Routing DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Routing Domain Module - Composition root
 *
 * DDD: Composition root for routing domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AppealRepositoryAdapter,
  CalibrationSampleRepositoryAdapter,
  PreemptRepositoryAdapter,
  ResolutionRepositoryAdapter,
  ResponseClockRepositoryAdapter,
  ReviewRepositoryAdapter,
  RightRepositoryAdapter,
  RoutingRepositoryAdapter,
  WorkItemRepositoryAdapter,
} from "@ddd/adapters/routing";
import { getIdGeneratorService } from "@ddd/adapters";
import type { AdapterDynamoDBClient } from "@ddd/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetRightsRecord,
  ExecuteGetRoutingDecision,
  ExecuteListAppeals,
  ExecuteListCalibrationSamples,
  ExecuteListResponseClocks,
  ExecuteListWorkItems,
  ExecuteOpenAppeal,
  ExecutePreemptResponseClock,
  ExecuteRecordHumanReview,
  ExecuteResolveAppeal,
  ExecuteSubmitWorkItem,
} from "@ddd/services/routing/usecases";
// Ports (interfaces)
import type {
  AppealRepository,
  CalibrationSampleRepository,
  PreemptRepository,
  ResolutionRepository,
  ResponseClockRepository,
  ReviewRepository,
  RightRepository,
  RoutingRepository,
  WorkItemRepository,
} from "@ddd/services/routing/ports";

export interface RoutingDomainModule {
  repos: {
    appeals: AppealRepository;
    calibrationSamples: CalibrationSampleRepository;
    preempts: PreemptRepository;
    resolutions: ResolutionRepository;
    responseClocks: ResponseClockRepository;
    reviews: ReviewRepository;
    rights: RightRepository;
    routings: RoutingRepository;
    workItems: WorkItemRepository;
  };
  useCases: {
    appeals: {
      get: ExecuteOpenAppeal;
      list: ExecuteListAppeals;
    };
    calibrationSamples: {
      list: ExecuteListCalibrationSamples;
    };
    preempts: {
      get: ExecutePreemptResponseClock;
    };
    resolutions: {
      get: ExecuteResolveAppeal;
    };
    responseClocks: {
      list: ExecuteListResponseClocks;
    };
    reviews: {
      get: ExecuteRecordHumanReview;
    };
    rights: {
      get: ExecuteGetRightsRecord;
    };
    routings: {
      get: ExecuteGetRoutingDecision;
    };
    workItems: {
      create: ExecuteSubmitWorkItem;
      list: ExecuteListWorkItems;
    };
  };
}

export function buildRoutingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): RoutingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      appeals?: AppealRepository;
      calibrationSamples?: CalibrationSampleRepository;
      preempts?: PreemptRepository;
      resolutions?: ResolutionRepository;
      responseClocks?: ResponseClockRepository;
      reviews?: ReviewRepository;
      rights?: RightRepository;
      routings?: RoutingRepository;
      workItems?: WorkItemRepository;
    } = {};

    obj.appeals = new AppealRepositoryAdapter(dynamoClient);
    obj.calibrationSamples = new CalibrationSampleRepositoryAdapter(dynamoClient);
    obj.preempts = new PreemptRepositoryAdapter(dynamoClient);
    obj.resolutions = new ResolutionRepositoryAdapter(dynamoClient);
    obj.responseClocks = new ResponseClockRepositoryAdapter(dynamoClient);
    obj.reviews = new ReviewRepositoryAdapter(dynamoClient);
    obj.rights = new RightRepositoryAdapter(dynamoClient);
    obj.routings = new RoutingRepositoryAdapter(dynamoClient);
    obj.workItems = new WorkItemRepositoryAdapter(dynamoClient);
    return {
      appeals: obj.appeals!,
      calibrationSamples: obj.calibrationSamples!,
      preempts: obj.preempts!,
      resolutions: obj.resolutions!,
      responseClocks: obj.responseClocks!,
      reviews: obj.reviews!,
      rights: obj.rights!,
      routings: obj.routings!,
      workItems: obj.workItems!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    appeals: {
      get: new ExecuteOpenAppeal(executionContext, idGenerator, repos.appeals),
      list: new ExecuteListAppeals(executionContext, idGenerator, repos.appeals),
    },
    calibrationSamples: {
      list: new ExecuteListCalibrationSamples(executionContext, idGenerator, repos.calibrationSamples),
    },
    preempts: {
      get: new ExecutePreemptResponseClock(executionContext, idGenerator, repos.preempts),
    },
    resolutions: {
      get: new ExecuteResolveAppeal(executionContext, idGenerator, repos.resolutions),
    },
    responseClocks: {
      list: new ExecuteListResponseClocks(executionContext, idGenerator, repos.responseClocks),
    },
    reviews: {
      get: new ExecuteRecordHumanReview(executionContext, idGenerator, repos.reviews),
    },
    rights: {
      get: new ExecuteGetRightsRecord(executionContext, idGenerator, repos.rights),
    },
    routings: {
      get: new ExecuteGetRoutingDecision(executionContext, idGenerator, repos.routings),
    },
    workItems: {
      create: new ExecuteSubmitWorkItem(executionContext, idGenerator, repos.workItems),
      list: new ExecuteListWorkItems(executionContext, idGenerator, repos.workItems),
    },
  };
  return { repos, useCases: useCases as RoutingDomainModule["useCases"] };
}
