/**
 * AutomationApproval Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/queues.openapi.types.js";
import { schemas } from "../schemas/queues.schemas.js";

/**
 * Entity: AutomationApprovalEntity
 * Description: Represents the AutomationApproval domain model.
 * Source: schemas.Queue
 * Type: Persisted Entity (x-dynamodb)
 */
export const AutomationApprovalEntitySchema = schemas.Queue;
export type AutomationApprovalEntity = components["schemas"]["Queue"];
