/**
 * ThresholdPolicy Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: queues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/queues.openapi.types.js";
import { schemas } from "../schemas/queues.schemas.js";

/**
 * Entity: ThresholdPolicyEntity
 * Description: Represents the ThresholdPolicy domain model.
 * Source: schemas.ThresholdPolicy
 * Type: Persisted Entity (x-dynamodb)
 */
export const ThresholdPolicyEntitySchema = schemas.ThresholdPolicy;
export type ThresholdPolicyEntity = components["schemas"]["ThresholdPolicy"];
