/**
 * GoldenSetRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GoldenSetRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GoldenSetRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GoldenSetRepository,
} from "@ddd/services/vendors";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GoldenSetRepositoryDdb } from "./golden-set-repository.ddb.js";

/**
 * GoldenSetRepositoryAdapter
 *
 * Implements GoldenSetRepository port for infrastructure layer.
 */
export class GoldenSetRepositoryAdapter implements GoldenSetRepository {
  private readonly ddb: GoldenSetRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GoldenSetRepositoryDdb(this.dynamoClient);
  }

  async listGoldenSets(input: Parameters<GoldenSetRepository['listGoldenSets']>[0]): Promise<Awaited<ReturnType<GoldenSetRepository['listGoldenSets']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listGoldenSets(input);
  }
}
