/**
 * VendorCutoverRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: vendors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VendorCutoverRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VendorCutoverRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VendorCutoverRepository,
} from "@ddd/services/vendors";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VendorCutoverRepositoryDdb } from "./vendor-cutover-repository.ddb.js";

/**
 * VendorCutoverRepositoryAdapter
 *
 * Implements VendorCutoverRepository port for infrastructure layer.
 */
export class VendorCutoverRepositoryAdapter implements VendorCutoverRepository {
  private readonly ddb: VendorCutoverRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VendorCutoverRepositoryDdb(this.dynamoClient);
  }

  async cutoverVendorTraffic(input: Parameters<VendorCutoverRepository['cutoverVendorTraffic']>[0]): Promise<Awaited<ReturnType<VendorCutoverRepository['cutoverVendorTraffic']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.cutoverVendorTraffic(input);
  }
}
