/**
 * WorkItem Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { WorkItemEntity } from "@ddd/core/routing/models/index.js";
import { routingSchemas } from "@ddd/core/routing";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rou";

export function createWorkItem(overrides: Partial<WorkItemEntity> = {}) {
  const raw = {
    id: overrides.id ?? `wit_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    queueId: overrides.queueId ?? faker.string.uuid(),
    receivedAt: overrides.receivedAt ?? new Date().toISOString(),
    state: overrides.state ?? "received",
    ...overrides,
  };

  return routingSchemas.WorkItem.parse(raw);
}

export function workItemBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createWorkItem(overrides));
}
