/**
 * CreatePreempt DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { PreemptResponseClockParams } from "@ddd/core/routing";

export function createCreatePreemptRequest(overrides: Partial<PreemptResponseClockParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
