/**
 * GetBenefitRecord handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getBenefitRecord } from "@ddd/api-server/domains/portfolio/handlers";
import type { PortfolioDDDDependencies } from "@ddd/api-server/domains/portfolio";
import { createBenefit as createBenefitEntity } from "@ddd/factories/portfolio";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ddd/tests/shared";
import { PORTFOLIO_USE_CASES } from "../__factories__/use-cases.js";

describe("GetBenefitRecord", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PortfolioDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PortfolioDDDDependencies>(
      PORTFOLIO_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createBenefitEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetBenefitRecord, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { queueId: entity.id };

    await getBenefitRecord(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetBenefitRecord.execute).toHaveBeenCalledWith(expect.objectContaining({ queueId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { queueId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetBenefitRecord, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getBenefitRecord(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
