/**
 * Routing Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: routing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { RoutingEntity } from "@ddd/core/routing/models/index.js";
import { routingSchemas } from "@ddd/core/routing";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rou";

export function createRouting(overrides: Partial<RoutingEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    decidedAt: overrides.decidedAt ?? new Date().toISOString(),
    lane: overrides.lane ?? "machine_final",
    workItemId: overrides.workItemId ?? `wit_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return routingSchemas.RoutingDecision.parse(raw);
}

export function routingBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRouting(overrides));
}
