/**
 * Repository interface for EgressRecord
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EgressRecordEntity
} from "../models/egress-record.entity.js";
import type {
  ListEgressRecordsParams
} from "../types/index.js";
/**
 * EgressRecordRepository Interface
 */
export interface EgressRecordRepository extends ReadRepository<EgressRecordEntity, string, ListEgressRecordsParams> {

}
