/**
 * Repository interface for Exposure
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ExposureEntity
} from "../models/exposure.entity.js";
/**
 * ExposureRepository Interface
 */
export interface ExposureRepository extends ReadRepository<ExposureEntity, string, Record<string, never>> {

}
