/**
 * Repository interface for Roadmap
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: portfolio
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RoadmapEntity
} from "../models/roadmap.entity.js";
import type {
  ListRoadmapEntriesParams
} from "../types/index.js";
/**
 * RoadmapRepository Interface
 */
export interface RoadmapRepository extends ReadRepository<RoadmapEntity, string, ListRoadmapEntriesParams> {

}
